export const styles: { [key: string]: React.CSSProperties } = {
    container: {
      height: '100dvh',
      width: '100vw',
      backgroundColor: '#0a0a0a',
      color: '#fff',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      direction: 'rtl',
      overflow: 'hidden',
      position: 'relative',
    },
    safeAreaWrapper: {
      height: '100%',
      width: '100%',
      maxWidth: '500px',
      margin: '0 auto',
      padding: '20px',
      display: 'flex',
      flexDirection: 'column',
    },
    stepContainer: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: '20px',
      width: '100%',
    },
    title: {
      fontSize: '28px',
      fontWeight: '800',
      color: '#ffd700',
      textAlign: 'center',
      marginBottom: '10px',
    },
    btn: {
      padding: '12px 20px',
      borderRadius: '12px',
      fontSize: '18px',
      fontWeight: 'bold',
      border: 'none',
      cursor: 'pointer',
      transition: 'all 0.2s',
    },
    hugePlayBtn: {
      width: '220px',
      padding: '15px',
      borderRadius: '50px',
      fontSize: '20px',
      fontWeight: 'bold',
      backgroundColor: '#ffd700',
      color: '#000',
      border: 'none',
      boxShadow: '0 4px 15px rgba(255, 215, 0, 0.3)',
      cursor: 'pointer',
      alignSelf: 'center',
    },
    teamCard: {
      padding: '15px',
      borderRadius: '15px',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      width: '100%',
    },
    playerTag: {
      padding: '8px 12px',
      backgroundColor: '#ffd700',
      color: '#000',
      borderRadius: '8px',
      fontSize: '14px',
      fontWeight: 'bold',
      margin: '4px',
      display: 'inline-block',
    },
    pauseOverlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100vw',
      height: '100dvh',
      backgroundColor: '#0a0a0a',
      zIndex: 1000,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '30px',
    },
    adjBtn: {
      width: '40px',
      height: '40px',
      borderRadius: '10px',
      border: '1px solid #ffd700',
      backgroundColor: 'transparent',
      color: '#ffd700',
      fontSize: '20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    }
  };