export type CategoryType = "KIDS" | "JUNIOR" | "TEEN" | "ADULT";

export interface WordItem {
  word: string;
  en: string;
  img?: string;
}

export const HEBREW_ROOM_CODES = [
  "עומר", "אריה", "בלון", "גמל", "דוב", "הרים", "וילון", "זמיר", "חלוץ", "טירה", "יונה",
  "כדור", "לחם", "מפתח", "נחש", "סוס", "ענן", "פרח", "צפור", "קפה", "רכב",
  "שעון", "תמר", "בית", "גינה", "חלון", "סולם", "מתנה", "דגל", "שוקו"
];

const KIDS_LIST = [
  { word: "מזגן", en: "air_conditioner", img: "/words/kids/air_conditioner.png" },
  { word: "נמלה", en: "ant", img: "/words/kids/ant.png" },
  { word: "תפוח", en: "apple", img: "/words/kids/apple.png" },
  { word: "אסטרונאוט", en: "astronaut", img: "/words/kids/astronaut.png" },
  { word: "בננה", en: "banana", img: "/words/kids/banana.png" },
  { word: "כדורסל", en: "basketball", img: "/words/kids/basketball.png" },
  { word: "עטלף", en: "bat", img: "/words/kids/bat.png" },
  { word: "סוללה", en: "battery", img: "/words/kids/battery.png" },
  { word: "דבורה", en: "bee", img: "/words/kids/bee.png" },
  { word: "אופניים", en: "bicycle", img: "/words/kids/bicycle.png" },
  { word: "מגפיים", en: "boots", img: "/words/kids/boots.png" },
  { word: "לחם", en: "bread", img: "/words/kids/bread.png" },
  { word: "דחפור", en: "bulldozer", img: "/words/kids/bulldozer.png" },
  { word: "אוטובוס", en: "bus", img: "/words/kids/bus.png" },
  { word: "פרפר", en: "butterfly", img: "/words/kids/butterfly.png" },
  { word: "מחשבון", en: "calculator", img: "/words/kids/calculator.png" },
  { word: "גמל", en: "camel", img: "/words/kids/camel.png" },
  { word: "מצלמה", en: "camera", img: "/words/kids/camera.png" },
  { word: "נר", en: "candle", img: "/words/kids/candle.png" },
  { word: "מכונית", en: "car", img: "/words/kids/car.png" },
  { word: "חתול", en: "cat", img: "/words/kids/cat.png" },
  { word: "צ'לו", en: "cello", img: "/words/kids/cello.png" },
  { word: "זיקית", en: "chameleon", img: "/words/kids/chameleon.png" },
  { word: "ברדלס", en: "cheetah", img: "/words/kids/cheetah.png" },
  { word: "שחמט", en: "chess", img: "/words/kids/chess.png" },
  { word: "אפרוח", en: "chick", img: "/words/kids/chick.png" },
  { word: "ענן", en: "cloud", img: "/words/kids/cloud.png" },
  { word: "תירס", en: "corn", img: "/words/kids/corn.png" },
  { word: "פרה", en: "cow", img: "/words/kids/cow.png" },
  { word: "סרטן", en: "crab", img: "/words/kids/crab.png" },
  { word: "מנוף", en: "crane", img: "/words/kids/crane.png" },
  { word: "מלפפון", en: "cucumber", img: "/words/kids/cucumber.png" },
  { word: "כוס", en: "cup", img: "/words/kids/cup.png" },
  { word: "כלב", en: "dog", img: "/words/kids/dog.png" },
  { word: "דלת", en: "door", img: "/words/kids/door.png" },
  { word: "מקדחה", en: "drill", img: "/words/kids/drill.png" },
  { word: "תופים", en: "drums", img: "/words/kids/drums.png" },
  { word: "ברווז", en: "duck", img: "/words/kids/duck.png" },
  { word: "פיל", en: "elephant", img: "/words/kids/elephant.png" },
  { word: "כבאי", en: "firefighter", img: "/words/kids/firefighter.png" },
  { word: "דג", en: "fish", img: "/words/kids/fish.png" },
  { word: "פרח", en: "flower", img: "/words/kids/flower.png" },
  { word: "חליל", en: "flute", img: "/words/kids/flute.png" },
  { word: "שועל", en: "fox", img: "/words/kids/fox.png" },
  { word: "מקרר", en: "fridge", img: "/words/kids/fridge.png" },
  { word: "צפרדע", en: "frog", img: "/words/kids/frog.png" },
  { word: "מתנה", en: "gift", img: "/words/kids/gift.png" },
  { word: "ג'ירפה", en: "giraffe", img: "/words/kids/giraffe.png" },
  { word: "ענבים", en: "grapes", img: "/words/kids/grapes.png" },
  { word: "דשא", en: "grass", img: "/words/kids/grass.png" },
  { word: "יד", en: "hand", img: "/words/kids/hand.png" },
  { word: "כובע", en: "hat", img: "/words/kids/hat.png" },
  { word: "אוזניות", en: "headphones", img: "/words/kids/headphones.png" },
  { word: "קיפוד", en: "hedgehog", img: "/words/kids/hedgehog.png" },
  { word: "מסוק", en: "helicopter", img: "/words/kids/helicopter.png" },
  { word: "היפופוטם", en: "hippopotamus", img: "/words/kids/hippopotamus.png" },
  { word: "סוס", en: "horse", img: "/words/kids/horse.png" },
  { word: "נקניקייה", en: "hotdog", img: "/words/kids/hotdog.png" },
  { word: "גלידה", en: "ice_cream", img: "/words/kids/ice_cream.png" },
  { word: "מפתח", en: "key", img: "/words/kids/key.png" },
  { word: "סולם", en: "ladder", img: "/words/kids/ladder.png" },
  { word: "חיפושית", en: "ladybug", img: "/words/kids/ladybug.png" },
  { word: "עלה", en: "leaf", img: "/words/kids/leaf.png" },
  { word: "אריה", en: "lion", img: "/words/kids/lion.png" },
  { word: "זכוכית מגדלת", en: "magnifying_glass", img: "/words/kids/magnifying_glass.png" },
  { word: "מדליה", en: "medal", img: "/words/kids/medal.png" },
  { word: "חלב", en: "milk", img: "/words/kids/milk.png" },
  { word: "קוף", en: "monkey", img: "/words/kids/monkey.png" },
  { word: "ירח", en: "moon", img: "/words/kids/moon.png" },
  { word: "אופנוע", en: "motorcycle", img: "/words/kids/motorcycle.png" },
  { word: "פטריה", en: "mushroom", img: "/words/kids/mushroom.png" },
  { word: "תפוז", en: "orange", img: "/words/kids/orange.png" },
  { word: "ינשוף", en: "owl", img: "/words/kids/owl.png" },
  { word: "תוכי", en: "parrot", img: "/words/kids/parrot.png" },
  { word: "טווס", en: "peacock", img: "/words/kids/peacock.png" },
  { word: "אגס", en: "pear", img: "/words/kids/pear.png" },
  { word: "פינגווין", en: "penguin", img: "/words/kids/penguin.png" },
  { word: "פלפל", en: "pepper", img: "/words/kids/pepper.png" },
  { word: "אננס", en: "pineapple", img: "/words/kids/pineapple.png" },
  { word: "פיצה", en: "pizza", img: "/words/kids/pizza.png" },
  { word: "פופקורן", en: "popcorn", img: "/words/kids/popcorn.png" },
  { word: "ארנב", en: "rabbit", img: "/words/kids/rabbit.png" },
  { word: "קרנף", en: "rhino", img: "/words/kids/rhino.png" },
  { word: "טבעת", en: "ring", img: "/words/kids/ring.png" },
  { word: "קורקינט", en: "scooter", img: "/words/kids/scooter.png" },
  { word: "עקרב", en: "scorpion", img: "/words/kids/scorpion.png" },
  { word: "כבשה", en: "sheep", img: "/words/kids/sheep.png" },
  { word: "נעליים", en: "shoes", img: "/words/kids/shoes.png" },
  { word: "חילזון", en: "snail", img: "/words/kids/snail.png" },
  { word: "נחש", en: "snake", img: "/words/kids/snake.png" },
  { word: "כדורגל", en: "soccer", img: "/words/kids/soccer.png" },
  { word: "סושי", en: "sushi", img: "/words/kids/sushi.png" },
  { word: "טנק", en: "tank", img: "/words/kids/tank.png" },
  { word: "אוהל", en: "tent", img: "/words/kids/tent.png" },
  { word: "עגבניה", en: "tomato", img: "/words/kids/tomato.png" },
  { word: "מברשת שיניים", en: "toothbrush", img: "/words/kids/toothbrush.png" },
  { word: "טרקטור", en: "tractor", img: "/words/kids/tractor.png" },
  { word: "רכבת", en: "train", img: "/words/kids/train.png" },
  { word: "עץ", en: "tree", img: "/words/kids/tree.png" },
  { word: "גביע", en: "trophy", img: "/words/kids/trophy.png" },
  { word: "משאית", en: "truck", img: "/words/kids/truck.png" },
  { word: "צב", en: "turtle", img: "/words/kids/turtle.png" },
  { word: "שואב אבק", en: "vacuum_cleaner", img: "/words/kids/vacuum_cleaner.png" },
  { word: "משרוקית", en: "whistle", img: "/words/kids/whistle.png" },
  { word: "זברה", en: "zebra", img: "/words/kids/zebra.png" }
];

const JUNIOR_ONLY = [
  { word: "טניס", en: "tennis", img: "/words/junior/tennis.png" },
  { word: "רולרבליידס", en: "rollerblades", img: "/words/junior/rollerblades.png" },
  { word: "מטוס סילון", en: "jet", img: "/words/junior/jet.png" },
  { word: "צוללן", en: "diver", img: "/words/junior/diver.png" },
  { word: "מדבר", en: "desert", img: "/words/junior/desert.png" },
  { word: "יער", en: "forest", img: "/words/junior/forest.png" },
  { word: "הר געש", en: "volcano", img: "/words/junior/volcano.png" },
  { word: "מפל", en: "waterfall", img: "/words/junior/waterfall.png" },
  { word: "סירה", en: "boat", img: "/words/junior/boat.png" },
  { word: "מזוודה", en: "suitcase", img: "/words/junior/suitcase.png" },
  { word: "ארנק", en: "wallet", img: "/words/junior/wallet.png" },
  { word: "מצפן", en: "compass", img: "/words/junior/compass.png" },
  { word: "גלובוס", en: "globe", img: "/words/junior/globe.png" },
  { word: "פטיש", en: "hammer", img: "/words/junior/hammer.png" },
  { word: "גשר", en: "bridge", img: "/words/junior/bridge.png" },
  { word: "כבל", en: "cable", img: "/words/junior/cable.png" },
  { word: "פנדה", en: "panda", img: "/words/junior/panda.png" },
  { word: "קואלה", en: "koala", img: "/words/junior/koala.png" },
  { word: "קנגורו", en: "kangaroo", img: "/words/junior/kangaroo.png" },
  { word: "גורילה", en: "gorilla", img: "/words/junior/gorilla.png" },
  { word: "תנין", en: "crocodile", img: "/words/junior/crocodile.png" },
  { word: "לווייתן", en: "whale", img: "/words/junior/whale.png" },
  { word: "דולפין", en: "dolphin", img: "/words/junior/dolphin.png" },
  { word: "כוכב ים", en: "starfish", img: "/words/junior/starfish.png" },
  { word: "פלמינגו", en: "flamingo", img: "/words/junior/flamingo.png" },
  { word: "ברבור", en: "swan", img: "/words/junior/swan.png" },
  { word: "סנאי", en: "squirrel", img: "/words/junior/squirrel.png" },
  { word: "אייל", en: "deer", img: "/words/junior/deer.png" },
  { word: "סטייק", en: "steak", img: "/words/junior/steak.png" },
  { word: "גבינה", en: "cheese", img: "/words/junior/cheese.png" },
  { word: "דבש", en: "honey", img: "/words/junior/honey.png" },
  { word: "שוקולד", en: "chocolate", img: "/words/junior/chocolate.png" },
  { word: "עוגה", en: "cake", img: "/words/junior/cake.png" },
  { word: "דונאט", en: "donut", img: "/words/junior/donut.png" },
  { word: "פנקייק", en: "pancake", img: "/words/junior/pancake.png" },
  { word: "וופל", en: "waffle", img: "/words/junior/waffle.png" },
  { word: "פאי", en: "pie", img: "/words/junior/pie.png" },
  { word: "גיטרה", en: "guitar", img: "/words/junior/guitar.png" },
  { word: "כינור", en: "violin", img: "/words/junior/violin.png" },
  { word: "חצוצרה", en: "trumpet", img: "/words/junior/trumpet.png" },
  { word: "נבל", en: "harp", img: "/words/junior/harp.png" },
  { word: "רקטה", en: "rocket", img: "/words/junior/rocket.png" },
  { word: "טירה", en: "castle", img: "/words/junior/castle.png" },
  { word: "טחנת רוח", en: "windmill", img: "/words/windmill.png" },
  { word: "סבון", en: "soap", img: "/words/junior/soap.png" },
  { word: "מנעול", en: "lock", img: "/words/junior/lock.png" },
  { word: "מטריה", en: "umbrella", img: "/words/junior/umbrella.png" },
  { word: "מבחנה", en: "test_tube", img: "/words/junior/test_tube.png" },
  { word: "ברק", en: "lightning", img: "/words/junior/lightning.png" },
  { word: "שימפנזה", en: "chimpanzee", img: "/words/junior/chimpanzee.png" },
  { word: "קוברה", en: "cobra", img: "/words/junior/cobra.png" },
  { word: "מדוזה", en: "jellyfish", img: "/words/junior/jellyfish.png" },
  { word: "יען", en: "ostrich", img: "/words/junior/ostrich.png" },
  { word: "לוטרה", en: "otter", img: "/words/junior/otter.png" },
  { word: "באולינג", en: "bowling", img: "/words/junior/bowling.png" },
  { word: "סיוף", en: "fencing", img: "/words/junior/fencing.png" },
  { word: "גולף", en: "golf", img: "/words/junior/golf.png" },
  { word: "סקי", en: "skiing", img: "/words/junior/skiing.png" },
  { word: "פלייר", en: "pliers", img: "/words/junior/pliers.png" },
  { word: "רחפן", en: "drone", img: "/words/junior/drone.png" }
];

const TEEN_ABSTRACT = [
  "אינסטגרם", "ויראלי", "לייק", "עוקבים", "סנאפצ'ט", "טיקטוק", "גיימר", "הופעה", "חברות", "מרד", "סטורי", "האשטאג", "סלפי", "טרנד", "משפיען", "מנוי", "תגובה", "שיתוף", "הודעה", "קבוצה", "שיחת וידאו", "אמוג'י", "סטיקר", "מם", "וירטואלי", "שרת", "פרופיל", "פרטיות", "חסימה", "דיווח", "מצלמה", "מיקרופון", "רמקול", "סוללה", "מטען", "קרינה", "מסך", "מקלדת", "עכבר", "אוזניות", "משחק", "תחרות", "ניצחון", "הפסד", "קבוצה", "אימון", "כושר", "תזונה", "בריאות", "שינה", "לימודים", "בית ספר", "מבחן", "ציון", "הפסקה", "חצר", "טיול", "מסע", "חופשה", "ים", "בריכה", "סרט", "קולנוע", "פופקורן", "שתייה", "אוכל", "מסעדה", "פיצה", "המבורגר", "צ'יפס", "גלידה", "ממתק", "שוקולד", "חטיף", "שתייה קלה", "מים", "מיץ", "סודה", "קפה", "תה", "שוקו", "חלב", "גבינה", "לחם", "חמאה", "ריבה", "דבש", "ביצה", "סלט", "ירקות", "פירות", "בשר", "עוף", "דג", "אורז", "פסטה", "תפוח אדמה", "מרק", "קינוח", "בגד", "חולצה", "מכנסיים", "שמלה", "חצאית", "מעיל", "סוודר", "נעליים", "גרביים", "כובע", "צעיף", "כפפות", "משקפיים", "שעון", "תיק", "ארנק", "מפתח", "טלפון", "מחשב", "טלוויזיה", "רדיו", "ספר", "מחברת", "עיפרון", "עט", "מחק", "סרגל", "מספריים", "דבק", "נייר", "צבע", "מכחול", "ציור", "פיסול", "ריקוד", "שירה", "נגינה", "גיטרה", "פסנתר", "תופים", "כינור", "חליל", "חצוצרה", "בית", "חדר", "מיטה", "ארון", "שולחן", "כיסא", "ספה", "שטיח", "חלון", "דלת", "גינה", "חצר", "רחוב", "עיר", "כפר", "מדינה", "עולם", "חלל", "שמיים", "שמש", "ירח", "כוכב", "ענן", "גשם", "שלג", "רוח", "חום", "קור", "אור", "חושך", "יום", "לילה", "בוקר", "צהריים", "ערב", "זמן", "שעה", "דקה", "שנייה", "תאריך", "שנה", "חודש", "שבוע", "יום הולדת", "חג", "מתנה", "מסיבה", "חברים", "משפחה", "אהבה", "שמחה", "צחוק", "חיוך", "דמעות", "כעס", "פחד", "הפתעה", "סקרנות", "חלום", "תקווה", "אומץ", "חופש", "שלום"
].map(w => ({ word: w, en: "" }));

const ADULT_ABSTRACT = [
  "משכנתא", "אינפלציה", "בירוקרטיה", "דירקטוריון", "אסטרטגיה", "גלובליזציה", "פנסיה", "נדל\"ן", "סטארט-אפ", "יזמות", "השקעות", "בורסה", "מניות", "ריבית", "מיסוי", "תקציב", "מאזן", "נזילות", "אשראי", "דירוג", "הסכם", "חוזה", "בוררות", "תביעה", "פסק דין", "חקיקה", "ממשל", "פוליטיקה", "דיפלומטיה", "יחסים בין-לאומיים", "ביטחון", "כלכלה", "חברה", "תרבות", "אמנות", "פילוסופיה", "אתיקה", "לוגיקה", "מדע", "טכנולוגיה", "חדשנות", "מחקר", "פיתוח", "הנדסה", "רפואיה", "משפטים", "חינוך", "תקשורת", "שיווק", "פרסום", "מיתוג", "מכירות", "שירות לקוחות", "ניהול", "מנהיגות", "עבודת צוות", "יצירתיות", "חשיבה ביקורתית", "פתרון בעיות", "קבלת החלטות", "ניהול זמן", "ניהול פרויקטים", "משאבי אנוש", "גיוס", "הכשרה", "רווחה", "סביבה", "קיימות", "שינוי אקלים", "אנרגיה", "תשתיות", "תחבורה", "עירוניות", "דמוגרפיה", "הגירה", "זהות", "קהילה", "התנדבות", "אחריות חברתית", "פילנתרופיה", "זכויות אדם", "חופש ביטוי", "שוויון", "צדק", "דמוקרטיה", "ליברליזם", "שמרנות", "סוציאליזם", "קפיטליזם", "היסטוריה", "מורשת", "מסורת", "דת", "רוחניות", "פסיכולוגיה", "אישיות", "התנהגות", "קוגניציה", "רגש", "מוטיבציה", "לחץ", "חוסן", "רווחה נפשית", "זוגיות", "הורות", "משפחה", "קריירה", "לימודים אקדמיים", "תואר", "מחקר", "מאמר", "כנס", "הרצאה", "דיון", "שיח", "דיאלוג", "פרספקטיבה", "תפיסה", "פרשנות", "משמעות", "ערך", "מטרה", "חזון", "שליחות", "הישג", "הצלחה", "כישלון", "למידה", "צמיחה", "התפתחות", "שינוי", "הסתגלות", "גמישות", "חדשנות", "יצירתיות", "דמיון", "השראה", "כישרון", "מיומנות", "מומחיות", "ניסיון", "ידע", "חוכמה", "בינה", "תבונה", "מודעות", "תשומת לב", "ריכוז", "זיכרון", "חשיבה", "הגיון", "אינטואיציה", "יצירה", "ביטוי", "תקשורת", "שפה", "ספרות", "שירה", "דרמה", "מוזיקה", "ציור", "פיסול", "אדריכלות", "עיצוב", "קולנוע", "תיאטרון", "מחול", "צילום", "מדיה", "אינטרנט", "רשתות חברתיות", "בינה מלאכותית", "רובוטיקה", "ננוטכנולוגיה", "ביוטכנולוגיה", "גנטיקה", "אסטרונומיה", "פיזיקה", "כימיה", "ביולוגיה", "מתמטיקה", "סטטיסטיקה", "נתונים", "מידע", "ידע", "חוכמה", "אמת", "מציאות", "קיום", "זמן", "מרחב", "אנרגיה", "חומר", "חיים", "תודעה", "נפש", "רוח", "אלוהים", "טבע", "יקום", "אינסוף", "פלא", "מסתורין", "יופי", "אסתטיקה", "הרמוניה", "איזון", "סימטריה", "קצב", "תנועה", "שינוי", "התפתחות", "אבולוציה", "היסטוריה", "זמן", "עתיד", "תקווה", "גורל", "בחירה", "חופש", "אחריות", "חובה", "זכות", "מוסר", "מצפון", "יושרה", "כבוד", "אמון", "נאמנות", "מסירות", "הקרבה", "חסד", "חמלה", "אמפתיה", "סובלנות", "סליחה", "פיוס", "שלום", "אחווה", "סולידריות", "שיתוף פעולה", "עזרה הדדית", "תרומה", "השפעה", "שינוי חברתי", "קידמה", "צדק חברתי", "שוויון הזדמנויות", "זכויות האזרח", "חופש המחשבה", "חופש האמונה", "חופש העיסוק", "חופש התנועה", "פרטיות", "אוטונומיה", "ריבונות", "עצמאות", "ביטחון אישי", "ביטחון תזונתי", "ביטחון אנרגטי", "חוסן לאומי", "יציבות", "שגשוג", "רווחה", "איכות חיים", "אושר", "סיפוק", "משמעות", "מימוש עצמי", "פוטנציאל", "שאיפה", "יעד", "חלום", "תשוקה", "הנאה", "תענוג", "שלווה", "רוגע", "איזון נפשי", "בריאות הגוף", "כושר גופני", "תזונה נבונה", "אורח חיים בריא", "מניעה", "טיפול", "שיקום", "החלמה", "התחדשות", "פריחה", "צמיחה", "שפע", "ברכה", "תודה", "הוקרה", "הערכה", "צניעות", "ענווה", "פשטות", "אותנטיות", "כנות", "אמת", "יופי", "טוב", "אור", "אהבה"
].map(w => ({ word: w, en: "" }));

export const WORD_DATABASE: Record<CategoryType, any[]> = {
  KIDS: KIDS_LIST,
  JUNIOR: [...KIDS_LIST, ...JUNIOR_ONLY],
  TEEN: [...KIDS_LIST, ...JUNIOR_ONLY, ...TEEN_ABSTRACT],
  ADULT: [...KIDS_LIST, ...JUNIOR_ONLY, ...TEEN_ABSTRACT, ...ADULT_ABSTRACT]
};