import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    height: '100dvh',
    width: '100vw',
    backgroundColor: '#0a0a0a',
    color: '#fff',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    direction: 'rtl',
    overflow: 'hidden',
    position: 'relative',
  },
  safeAreaWrapper: {
    height: '100%',
    width: '100%',
    maxWidth: '500px',
    margin: '0 auto',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
  },
  flexLayout: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  stepContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '20px',
    width: '100%',
  },
  title: {
    fontSize: '28px',
    fontWeight: '800',
    color: '#ffd700',
    textAlign: 'center',
    marginBottom: '10px',
  },
  formCard: {
    width: '100%',
    maxWidth: '350px',
    padding: '25px',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '24px',
    marginTop: '20px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  input: {
    padding: '15px',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    color: '#fff',
    fontSize: '16px',
    textAlign: 'center',
  },
  goldButton: {
    padding: '15px',
    borderRadius: '12px',
    backgroundColor: '#ffd700',
    color: '#000',
    border: 'none',
    fontSize: '18px',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(255, 215, 0, 0.2)',
  },
  btn: {
    padding: '12px 20px',
    borderRadius: '12px',
    fontSize: '16px',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  hugePlayBtn: {
    width: '220px',
    padding: '15px',
    borderRadius: '50px',
    fontSize: '20px',
    fontWeight: 'bold',
    backgroundColor: '#ffd700',
    color: '#000',
    border: 'none',
    boxShadow: '0 4px 15px rgba(255, 215, 0, 0.3)',
    cursor: 'pointer',
    alignSelf: 'center',
    marginTop: '20px',
  },
  teamCard: {
    padding: '15px',
    borderRadius: '15px',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    width: '100%',
  },
  playerTag: {
    padding: '8px 12px',
    backgroundColor: '#ffd700',
    color: '#000',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 'bold',
    margin: '4px',
    display: 'inline-block',
  }
};