export const styles: { [key: string]: React.CSSProperties } = {
    container: {
      height: '100dvh',
      width: '100vw',
      backgroundColor: '#0a0a0a',
      color: '#fff',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      direction: 'rtl',
      overflow: 'hidden',
      position: 'relative',
    },
    safeAreaWrapper: {
      height: '100%',
      width: '100%',
      maxWidth: '500px',
      margin: '0 auto',
      padding: '20px',
      display: 'flex',
      flexDirection: 'column',
    },
    stepContainer: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: '20px',
      width: '100%',
    },
    title: {
      fontSize: '28px',
      fontWeight: '800',
      color: '#ffd700',
      textAlign: 'center',
      marginBottom: '10px',
    },
    // טוגל מעוצב
    toggleContainer: {
      display: 'flex',
      backgroundColor: '#1a1a1a',
      borderRadius: '50px',
      padding: '4px',
      width: '100%',
      maxWidth: '320px',
      border: '1px solid rgba(255,255,255,0.1)',
    },
    toggleOption: {
      flex: 1,
      padding: '12px',
      textAlign: 'center',
      borderRadius: '50px',
      fontSize: '16px',
      fontWeight: 'bold',
      cursor: 'pointer',
      transition: '0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    },
    // כפתור התחל משחק (ממורכז וברוחב 220px)
    hugePlayBtn: {
      width: '220px',
      padding: '16px',
      borderRadius: '50px',
      fontSize: '20px',
      fontWeight: 'bold',
      backgroundColor: '#ffd700',
      color: '#000',
      border: 'none',
      boxShadow: '0 4px 15px rgba(255, 215, 0, 0.3)',
      cursor: 'pointer',
      marginTop: 'auto',
      marginBottom: '20px',
    },
    // כפתור X ליציאה
    exitBtn: {
      position: 'absolute',
      top: '15px',
      left: '15px',
      background: 'rgba(255,255,255,0.1)',
      color: '#fff',
      border: 'none',
      borderRadius: '50%',
      width: '40px',
      height: '40px',
      fontSize: '20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 100,
      cursor: 'pointer',
    },
    // כרטיס קבוצה
    teamCard: {
      padding: '15px',
      borderRadius: '15px',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      width: '100%',
      transition: '0.2s',
    },
    playerTag: {
      padding: '8px 12px',
      backgroundColor: '#ffd700',
      color: '#000',
      borderRadius: '8px',
      fontSize: '14px',
      fontWeight: 'bold',
      margin: '4px',
      display: 'inline-block',
      userSelect: 'none',
      touchAction: 'none', // חשוב לגרירה מהירה
    },
    btn: {
      padding: '10px 15px',
      borderRadius: '10px',
      fontSize: '15px',
      fontWeight: 'bold',
      border: 'none',
      cursor: 'pointer',
    }
  };