export type CategoryType = "KIDS" | "JUNIOR" | "TEEN" | "ADULT";
export type DifficultyLevel = "VARIABLE" | "EASY" | "MEDIUM" | "HARD";

export interface WordItem {
  word: string;
  en: string;
  img?: string;
}

// --- מאגר KIDS (105 פריטים) ---
const KIDS_LIST: WordItem[] = [
  { word: "מזגן", en: "air_conditioner", img: "/words/kids/air_conditioner.webp" },
  { word: "נמלה", en: "ant", img: "/words/kids/ant.webp" },
  { word: "תפוח", en: "apple", img: "/words/kids/apple.webp" },
  { word: "אסטרונאוט", en: "astronaut", img: "/words/kids/astronaut.webp" },
  { word: "בננה", en: "banana", img: "/words/kids/banana.webp" },
  { word: "כדורסל", en: "basketball", img: "/words/kids/basketball.webp" },
  { word: "עטלף", en: "bat", img: "/words/kids/bat.webp" },
  { word: "סוללה", en: "battery", img: "/words/kids/battery.webp" },
  { word: "דבורה", en: "bee", img: "/words/kids/bee.webp" },
  { word: "אופניים", en: "bicycle", img: "/words/kids/bicycle.webp" },
  { word: "מגפיים", en: "boots", img: "/words/kids/boots.webp" },
  { word: "לחם", en: "bread", img: "/words/kids/bread.webp" },
  { word: "דחפור", en: "bulldozer", img: "/words/kids/bulldozer.webp" },
  { word: "אוטובוס", en: "bus", img: "/words/kids/bus.webp" },
  { word: "פרפר", en: "butterfly", img: "/words/kids/butterfly.webp" },
  { word: "מחשבון", en: "calculator", img: "/words/kids/calculator.webp" },
  { word: "גמל", en: "camel", img: "/words/kids/camel.webp" },
  { word: "מצלמה", en: "camera", img: "/words/kids/camera.webp" },
  { word: "נר", en: "candle", img: "/words/kids/candle.webp" },
  { word: "מכונית", en: "car", img: "/words/kids/car.webp" },
  { word: "חתול", en: "cat", img: "/words/kids/cat.webp" },
  { word: "צ'לו", en: "cello", img: "/words/kids/cello.webp" },
  { word: "זיקית", en: "chameleon", img: "/words/kids/chameleon.webp" },
  { word: "ברדלס", en: "cheetah", img: "/words/kids/cheetah.webp" },
  { word: "שחמט", en: "chess", img: "/words/kids/chess.webp" },
  { word: "אפרוח", en: "chick", img: "/words/kids/chick.webp" },
  { word: "ענן", en: "cloud", img: "/words/kids/cloud.webp" },
  { word: "תירס", en: "corn", img: "/words/kids/corn.webp" },
  { word: "פרה", en: "cow", img: "/words/kids/cow.webp" },
  { word: "סרטן", en: "crab", img: "/words/kids/crab.webp" },
  { word: "מנוף", en: "crane", img: "/words/kids/crane.webp" },
  { word: "מלפפון", en: "cucumber", img: "/words/kids/cucumber.webp" },
  { word: "כוס", en: "cup", img: "/words/kids/cup.webp" },
  { word: "כלב", en: "dog", img: "/words/kids/dog.webp" },
  { word: "דלת", en: "door", img: "/words/kids/door.webp" },
  { word: "מקדחה", en: "drill", img: "/words/kids/drill.webp" },
  { word: "תופים", en: "drums", img: "/words/kids/drums.webp" },
  { word: "ברווז", en: "duck", img: "/words/kids/duck.webp" },
  { word: "פיל", en: "elephant", img: "/words/kids/elephant.webp" },
  { word: "כבאי", en: "firefighter", img: "/words/kids/firefighter.webp" },
  { word: "דג", en: "fish", img: "/words/kids/fish.webp" },
  { word: "פרח", en: "flower", img: "/words/kids/flower.webp" },
  { word: "חליל", en: "flute", img: "/words/kids/flute.webp" },
  { word: "שועל", en: "fox", img: "/words/kids/fox.webp" },
  { word: "מקרר", en: "fridge", img: "/words/kids/fridge.webp" },
  { word: "צפרדע", en: "frog", img: "/words/kids/frog.webp" },
  { word: "מתנה", en: "gift", img: "/words/kids/gift.webp" },
  { word: "ג'ירפה", en: "giraffe", img: "/words/kids/giraffe.webp" },
  { word: "ענבים", en: "grapes", img: "/words/kids/grapes.webp" },
  { word: "דשא", en: "grass", img: "/words/kids/grass.webp" },
  { word: "יד", en: "hand", img: "/words/kids/hand.webp" },
  { word: "כובע", en: "hat", img: "/words/kids/hat.webp" },
  { word: "אוזניות", en: "headphones", img: "/words/kids/headphones.webp" },
  { word: "קיפוד", en: "hedgehog", img: "/words/kids/hedgehog.webp" },
  { word: "מסוק", en: "helicopter", img: "/words/kids/helicopter.webp" },
  { word: "היפופוטם", en: "hippopotamus", img: "/words/kids/hippopotamus.webp" },
  { word: "סוס", en: "horse", img: "/words/kids/horse.webp" },
  { word: "נקניקייה", en: "hotdog", img: "/words/kids/hotdog.webp" },
  { word: "גלידה", en: "ice_cream", img: "/words/kids/ice_cream.webp" },
  { word: "מפתח", en: "key", img: "/words/kids/key.webp" },
  { word: "סולם", en: "ladder", img: "/words/kids/ladder.webp" },
  { word: "חיפושית", en: "ladybug", img: "/words/kids/ladybug.webp" },
  { word: "עלה", en: "leaf", img: "/words/kids/leaf.webp" },
  { word: "אריה", en: "lion", img: "/words/kids/lion.webp" },
  { word: "זכוכית מגדלת", en: "magnifying_glass", img: "/words/kids/magnifying_glass.webp" },
  { word: "מדליה", en: "medal", img: "/words/kids/medal.webp" },
  { word: "חלב", en: "milk", img: "/words/kids/milk.webp" },
  { word: "קוף", en: "monkey", img: "/words/kids/monkey.webp" },
  { word: "ירח", en: "moon", img: "/words/kids/moon.webp" },
  { word: "אופנוע", en: "motorcycle", img: "/words/kids/motorcycle.webp" },
  { word: "פטריה", en: "mushroom", img: "/words/kids/mushroom.webp" },
  { word: "תפוז", en: "orange", img: "/words/kids/orange.webp" },
  { word: "ינשוף", en: "owl", img: "/words/kids/owl.webp" },
  { word: "תוכי", en: "parrot", img: "/words/kids/parrot.webp" },
  { word: "טווס", en: "peacock", img: "/words/kids/peacock.webp" },
  { word: "אגס", en: "pear", img: "/words/kids/pear.webp" },
  { word: "פינגווין", en: "penguin", img: "/words/kids/penguin.webp" },
  { word: "פלפל", en: "pepper", img: "/words/kids/pepper.webp" },
  { word: "אננס", en: "pineapple", img: "/words/kids/pineapple.webp" },
  { word: "פיצה", en: "pizza", img: "/words/kids/pizza.webp" },
  { word: "פופקורן", en: "popcorn", img: "/words/kids/popcorn.webp" },
  { word: "ארנב", en: "rabbit", img: "/words/kids/rabbit.webp" },
  { word: "קרנף", en: "rhino", img: "/words/kids/rhino.webp" },
  { word: "טבעת", en: "ring", img: "/words/kids/ring.webp" },
  { word: "קורקינט", en: "scooter", img: "/words/kids/scooter.webp" },
  { word: "עקרב", en: "scorpion", img: "/words/kids/scorpion.webp" },
  { word: "כבשה", en: "sheep", img: "/words/kids/sheep.webp" },
  { word: "נעליים", en: "shoes", img: "/words/kids/shoes.webp" },
  { word: "חילזון", en: "snail", img: "/words/kids/snail.webp" },
  { word: "נחש", en: "snake", img: "/words/kids/snake.webp" },
  { word: "כדורגל", en: "soccer", img: "/words/kids/soccer.webp" },
  { word: "סושי", en: "sushi", img: "/words/kids/sushi.webp" },
  { word: "טנק", en: "tank", img: "/words/kids/tank.webp" },
  { word: "אוהל", en: "tent", img: "/words/kids/tent.webp" },
  { word: "עגבניה", en: "tomato", img: "/words/kids/tomato.webp" },
  { word: "מברשת שיניים", en: "toothbrush", img: "/words/kids/toothbrush.webp" },
  { word: "טרקטור", en: "tractor", img: "/words/kids/tractor.webp" },
  { word: "רכבת", en: "train", img: "/words/kids/train.webp" },
  { word: "עץ", en: "tree", img: "/words/kids/tree.webp" },
  { word: "גביע", en: "trophy", img: "/words/kids/trophy.webp" },
  { word: "משאית", en: "truck", img: "/words/kids/truck.webp" },
  { word: "צב", en: "turtle", img: "/words/kids/turtle.webp" },
  { word: "שואב אבק", en: "vacuum_cleaner", img: "/words/kids/vacuum_cleaner.webp" },
  { word: "משרוקית", en: "whistle", img: "/words/kids/whistle.webp" },
  { word: "זברה", en: "zebra", img: "/words/kids/zebra.webp" }
];

// --- תוספות JUNIOR (139 פריטים) ---
const JUNIOR_ONLY: WordItem[] = [
  { word: "טניס", en: "tennis", img: "/words/junior/tennis.webp" },
  { word: "רולרבליידס", en: "rollerblades", img: "/words/junior/rollerblades.webp" },
  { word: "מטוס סילון", en: "jet", img: "/words/junior/jet.webp" },
  { word: "צוללן", en: "diver", img: "/words/junior/diver.webp" },
  { word: "מדבר", en: "desert", img: "/words/junior/desert.webp" },
  { word: "יער", en: "forest", img: "/words/junior/forest.webp" },
  { word: "הר געש", en: "volcano", img: "/words/junior/volcano.webp" },
  { word: "מפל", en: "waterfall", img: "/words/junior/waterfall.webp" },
  { word: "סירה", en: "boat", img: "/words/junior/boat.webp" },
  { word: "מזוודה", en: "suitcase", img: "/words/junior/suitcase.webp" },
  { word: "ארנק", en: "wallet", img: "/words/junior/wallet.webp" },
  { word: "מצפן", en: "compass", img: "/words/junior/compass.webp" },
  { word: "גלובוס", en: "globe", img: "/words/junior/globe.webp" },
  { word: "פטיש", en: "hammer", img: "/words/junior/hammer.webp" },
  { word: "גשר", en: "bridge", img: "/words/junior/bridge.webp" },
  { word: "כבל", en: "cable", img: "/words/junior/cable.webp" },
  { word: "פנדה", en: "panda", img: "/words/junior/panda.webp" },
  { word: "קואלה", en: "koala", img: "/words/junior/koala.webp" },
  { word: "קנגורו", en: "kangaroo", img: "/words/junior/kangaroo.webp" },
  { word: "גורילה", en: "gorilla", img: "/words/junior/gorilla.webp" },
  { word: "תנין", en: "crocodile", img: "/words/junior/crocodile.webp" },
  { word: "לווייתן", en: "whale", img: "/words/junior/whale.webp" },
  { word: "דולפין", en: "dolphin", img: "/words/junior/dolphin.webp" },
  { word: "כוכב ים", en: "starfish", img: "/words/junior/starfish.webp" },
  { word: "פלמינגו", en: "flamingo", img: "/words/junior/flamingo.webp" },
  { word: "ברבור", en: "swan", img: "/words/junior/swan.webp" },
  { word: "סנאי", en: "squirrel", img: "/words/junior/squirrel.webp" },
  { word: "אייל", en: "deer", img: "/words/junior/deer.webp" },
  { word: "סטייק", en: "steak", img: "/words/junior/steak.webp" },
  { word: "גבינה", en: "cheese", img: "/words/junior/cheese.webp" },
  { word: "דבש", en: "honey", img: "/words/junior/honey.webp" },
  { word: "שוקולד", en: "chocolate", img: "/words/junior/chocolate.webp" },
  { word: "עוגה", en: "cake", img: "/words/junior/cake.webp" },
  { word: "דונאט", en: "donut", img: "/words/junior/donut.webp" },
  { word: "פנקייק", en: "pancake", img: "/words/junior/pancake.webp" },
  { word: "וופל", en: "waffle", img: "/words/junior/waffle.webp" },
  { word: "פאי", en: "pie", img: "/words/junior/pie.webp" },
  { word: "גיטרה", en: "guitar", img: "/words/junior/guitar.webp" },
  { word: "כינור", en: "violin", img: "/words/junior/violin.webp" },
  { word: "חצוצרה", en: "trumpet", img: "/words/junior/trumpet.webp" },
  { word: "נבל", en: "harp", img: "/words/junior/harp.webp" },
  { word: "רקטה", en: "rocket", img: "/words/junior/rocket.webp" },
  { word: "טירה", en: "castle", img: "/words/junior/castle.webp" },
  { word: "טחנת רוח", en: "windmill", img: "/words/junior/windmill.webp" },
  { word: "סבון", en: "soap", img: "/words/junior/soap.webp" },
  { word: "מנעול", en: "lock", img: "/words/junior/lock.webp" },
  { word: "מטריה", en: "umbrella", img: "/words/junior/umbrella.webp" },
  { word: "מבחנה", en: "test_tube", img: "/words/junior/test_tube.webp" },
  { word: "ברק", en: "lightning", img: "/words/junior/lightning.webp" },
  { word: "שימפנזה", en: "chimpanzee", img: "/words/junior/chimpanzee.webp" },
  { word: "קוברה", en: "cobra", img: "/words/junior/cobra.webp" },
  { word: "מדוזה", en: "jellyfish", img: "/words/junior/jellyfish.webp" },
  { word: "יען", en: "ostrich", img: "/words/junior/ostrich.webp" },
  { word: "לוטרה", en: "otter", img: "/words/junior/otter.webp" },
  { word: "באולינג", en: "bowling", img: "/words/junior/bowling.webp" },
  { word: "סיוף", en: "fencing", img: "/words/junior/fencing.webp" },
  { word: "גולף", en: "golf", img: "/words/junior/golf.webp" },
  { word: "סקי", en: "skiing", img: "/words/junior/skiing.webp" },
  { word: "פלייר", en: "pliers", img: "/words/junior/pliers.webp" },
  { word: "רחפן", en: "drone", img: "/words/junior/drone.webp" },
  { word: "מיקרוסקופ", en: "microscope", img: "/words/junior/microscope.webp" },
  { word: "טלסקופ", en: "telescope", img: "/words/junior/telescope.webp" },
  { word: "מצנח", en: "parachute", img: "/words/junior/parachute.webp" },
  { word: "קליידוסקופ", en: "kaleidoscope", img: "/words/junior/kaleidoscope.webp" },
  { word: "פרסה", en: "horseshoe", img: "/words/junior/horseshoe.webp" },
  { word: "מגנט", en: "magnet", img: "/words/junior/magnet.webp" },
  { word: "עוגן", en: "anchor", img: "/words/junior/anchor.webp" },
  { word: "משקפת", en: "binoculars", img: "/words/junior/binoculars.webp" },
  { word: "סטטוסקופ", en: "stethoscope", img: "/words/junior/stethoscope.webp" }
];

// --- מאגר TEEN (מושגים מופשטים) ---
const TEEN_ONLY: WordItem[] = [
  "אינסטגרם", "ויראלי", "לייק", "עוקבים", "סנאפצ'ט", "טיקטוק", "גיימר", "הופעה", "חברות", "מרד", "סטורי", "האשטאג", "סלפי", "טרנד", "משפיען", "מנוי", "תגובה", "שיתוף", "הודעה", "שיחת וידאו", "אמוג'י", "סטיקר", "מם", "וירטואלי", "שרת", "פרופיל", "פרטיות", "חסימה", "דיווח", "קרינה", "מבחן בגרות", "רישיון נהיגה", "פסיכומטרי", "מחנה קיץ", "שיעור חופשי", "הברזה", "יוטיוב", "נטפליקס", "ספוטיפיי", "פלייליסט", "פודקאסט", "גיימינג", "סטרימינג", "ווטסאפ", "קבוצה", "סטטוס", "התראות", "מצב טיסה", "טעינה", "ווייפיי", "בלוטוס", "אפליקציה", "קוד", "תוכנה", "חומרה", "ענן", "סייבר", "האקר", "סיסמה", "אימות", "ספאם", "באג", "עדכון", "גרסה", "הורדה", "העלאה", "גיבוי", "שיחזור", "חיפוש", "לינק", "אתר", "דפדפן", "מנוע חיפוש", "פרסומת", "ספונסר", "קמפיין", "השקה", "הנחה", "מבצע", "קופון", "הזמנה", "משלוח", "שליח", "חבילה", "דואר", "כתובת", "מיקוד", "מפה", "ניווט", "ווייז", "תנועה", "פקק", "רמזור", "צומת", "כביש", "מדרכה", "מעבר חצייה", "גשר", "מנהרה", "רכבת", "אוטובוס", "מונית", "טיסה", "דרכון", "מזוודה", "חופשה", "מלון", "צימר", "קמפינג", "טיול", "מסלול", "נוף", "טבע", "סביבה", "זיהום", "מיחזור", "אנרגיה", "חשמל", "מים", "אדמה", "אוויר", "שמיים", "שמש", "ירח", "כוכבים", "מזג אוויר", "תחזית", "סערה", "גשם", "שלג", "רוח", "חום", "לחות", "טמפרטורה", "עונה", "חורף", "אביב", "קיץ", "סתיו", "חג", "מועד", "מסיבה", "אירוע", "חתונה", "בר מצווה", "יומולדת", "מתנה", "ברכה", "חיוך", "צחוק", "שמחה", "אושר", "אהבה", "חברות", "נאמנות", "כבוד", "יושר", "אומץ", "חופש", "עצמאות", "אחריות", "סבלנות", "הצלחה", "ניצחון", "הישג", "מטרה", "חלום", "תקווה", "עתיד", "זיכרון", "נוסטלגיה", "הווה", "זמן", "שעה", "רגע", "הזדמנונות", "בחירה", "החלטה", "שינוי", "שיפור", "למידה", "ניסיון", "ידע", "חוכמה", "סקרנות", "דמיון", "יצירתיות", "כשרון", "אומנות", "מוזיקה", "קולנוע", "ספרות", "תיאטרון", "ריקוד", "עיצוב", "אופנה", "סגנון", "יופי", "אסתטיקה", "ביטוי עצמי", "זהות", "אישיות", "אופי", "מצפון", "ערכים"
].map(w => ({ word: w, en: "" }));

// --- מאגר ADULT ---
const ADULT_ONLY: WordItem[] = [
  "משכנתא", "אינפלציה", "בירוקרטיה", "דירקטוריון", "אסטרטגיה", "גלובליזציה", "פנסיה", "נדל\"ן", "סטארט-אפ", "יזמות", "השקעות", "בורסה", "מניות", "ריבית", "מיסוי", "תקציב", "נזילות", "אשראי", "דירוג", "הסכם", "בוררות", "תביעה", "פסק דין", "חקיקה", "ממשל", "פוליטיקה", "דיפלומטיה", "ביטחון", "כלכלה", "חברה", "תרבות", "אתיקה", "לוגיקה", "מדע", "חדשנות", "מחקר", "פיתוח", "הנדסה", "רפואה", "משפטים", "חינוך", "שיווק", "פרסום", "מיתוג", "מכירות", "שירות לקוחות", "ניהול", "מנהיגות", "עבודת צוות", "יצירתיות", "חשיבה ביקורתית", "פתרון בעיות", "קבלת החלטות", "ניהול זמן", "ניהול פרויקטים", "משאבי אנוש", "גיוס", "הכשרה", "רווחה", "סביבה", "קיימות", "שינוי אקלים", "אנרגיה", "תשתיות", "תחבורה", "עירוניות", "דמוגרפיה", "הגירה", "זהות", "קהילה", "התנדבות", "אחריות חברתית", "פילנתרופיה", "זכויות אדם", "שוויון", "צדק", "דמוקרטיה", "ליברליזם", "סוציאליזם", "קפיטליזם", "היסטוריה", "מורשת", "מסורת", "דת", "רוחניות", "פסיכולוגיה", "אישיות", "התנהגות", "קוגניציה", "רגש", "מוטיבציה", "לחץ", "חוסן", "רווחה נפשית", "זוגיות", "הורות", "משפחה", "קריירה", "לימודים אקדמיים", "תואר", "מחקר", "מאמר", "כנס", "הרצאה", "דיון", "שיח", "פרספקטיבה", "תפיסה", "פרשנות", "משמעות", "ערך", "מטרה", "חזון", "שליחות", "הישג", "הצלחה", "כישלון", "למידה", "צמיחה", "התפתחות", "שינוי", "הסתגלות", "גמישות", "יצירתיות", "דמיון", "השראה", "כישרון", "מיומנות", "מומחיות", "ניסיון", "ידע", "חוכמה", "בינה", "תבונה", "מודעות", "תשומת לב", "ריכוז", "זיכרון", "חשיבה", "הגיון", "אינטואיציה", "יצירה", "ביטוי", "תקשורת", "שפה", "ספרות", "שירה", "דרמה", "מוזיקה", "ציור", "פיסול", "אדריכלות", "עיצוב", "קולנוע", "תיאטרון", "מחול", "צילום", "מדיה", "אינטרנט", "רשתות חברתיות", "בינה מלאכולית", "רובוטיקה", "ננוטכנולוגיה", "ביוטכנולוגיה", "גנטיקה", "אסטרונומיה", "פיזיקה", "כימיה", "ביולוגיה", "מתמטיקה", "סטטיסטיקה", "נתונים", "מידע", "אמת", "מציאות", "קיום", "זמן", "מרחב", "אנרגיה", "חומר", "חיים", "תודעה", "נפש", "רוח", "אלוהים", "יקום", "אינסוף", "פלא", "מסתורין", "יופי", "אסתטיקה", "הרמוניה", "איזון", "סימטריה", "קצב", "תנועה", "אבולוציה", "עתיד", "תקווה", "גורל", "בחירה", "חופש", "אחריות", "חובה", "זכות", "מוסר", "מצפון", "יושרה", "כבוד", "אמון", "נאמנות", "מסירות", "הקרבה", "חסד", "חמלה", "אמפתיה", "סובלנות", "סליחה", "פיוס", "שלום", "אחווה", "סולידריות", "תרומה", "השפעה", "קידמה", "צדק חברתי", "שוויון הזדמנויות", "זכויות האזרח", "חופש המחשבה", "חופש האמונה", "פרטיות", "אוטונומיה", "ריבונות", "עצמאות", "ביטחון אישי", "חוסן לאומי", "יציבות", "שגשוג", "רווחה", "איכות חיים", "אושר", "סיפוק", "מימוש עצמי", "פוטנציאל", "שאיפה", "יעד", "חלום", "תשוקה", "הנאה", "תענוג", "שלווה", "רוגע", "איזון נפשי", "בריאות הגוף", "כושר גופני", "אורח חיים בריא", "מניעה", "טיפול", "שיקום", "החלמה", "התחדשות", "פריחה", "צמיחה", "שפע", "ברכה", "תודה", "הוקרה", "הערכה", "צניעות", "ענווה", "פשטות", "אותנטיות", "כנות", "יוקרה", "מוניטין", "סמכות", "יוזמה", "מרץ", "התמדה", "נחישות", "עקביות", "שיטתיות", "יסודיות", "דיוק", "מהירות", "יעילות", "תפוקה", "ביצוע", "תוצאה", "משוב", "ביקורת", "תיקון", "לקח", "מסקנה", "תובנה", "הבנה", "יכולת", "אפשרות", "סיכוי", "סיכון", "אתגר", "מכשול", "קושי", "משבר", "קונפליקט", "דילמה", "ספק", "ודאות", "ביטחון", "אמונה", "אופטימיות", "פסימיות", "ריאליזם", "אידיאליזם", "פרגמטיזם", "רציונליזם", "אמפיריזם", "ספקנות", "סקרנות", "פליאה", "הערצה", "יראת כבוד", "כרת", "חסד", "גאולה", "נצח", "קדושה", "חולין", "טקס", "סמל", "מיתוס", "נרטיב", "סיפור", "שיר", "מחול", "משחק", "שעשוע", "הומור", "אירוניה", "סאטירה", "פארודיה", "טקס", "חגיגה", "משתה", "סעודה", "מפגש", "שיחה", "דיון", "ויכוח", "דיאלוג", "הקשבה", "הבנה", "הזדהות", "שותפות", "קהילה", "שייכות", "בית", "מולדת", "שורשים", "מורשת", "עבר", "הווה", "עתיד", "גורל", "חיים", "מוות", "קיום", "משמעות", "נצח", "אינסוף", "אחדות", "ריבוי", "גיוון", "שוני", "אחרות", "קבלה", "אהבה", "חסד", "אמת", "יופי", "טוב", "אור", "שלום"
].map(w => ({ word: w, en: "" }));

export const WORD_DATABASE: Record<CategoryType, WordItem[]> = {
  KIDS: KIDS_LIST,
  JUNIOR: [...KIDS_LIST, ...JUNIOR_ONLY],
  TEEN: [...KIDS_LIST, ...JUNIOR_ONLY, ...TEEN_ONLY],
  ADULT: [...KIDS_LIST, ...JUNIOR_ONLY, ...TEEN_ONLY, ...ADULT_ONLY]
};

export const HEBREW_ROOM_CODES = [
  "עומר", "אריה", "בלון", "גמל", "דוב", "הרים", "וילון", "זמיר", "חלוץ", "טירה", "יונה",
  "כדור", "לחם", "מפתח", "נחש", "סוס", "ענן", "פרח", "צפור", "קפה", "רכב",
  "שעון", "תמר", "בית", "גינה", "חלון", "סולם", "מתנה", "דגל", "שוקו"
];