import { WordItem } from "../../game.config";

export const JUNIOR_WORDS: WordItem[] = [
  { word: "מזגן", en: "Air Conditioner", img: "/words/junior/air_conditioner.webp" },
  { word: "תפוח", en: "Apple", img: "/words/junior/apple.webp" },
  { word: "אסטרונאוט", en: "Astronaut", img: "/words/junior/astronaut.webp" },
  { word: "בננה", en: "Banana", img: "/words/junior/banana.webp" },
  { word: "כדורסל", en: "Basketball", img: "/words/junior/basketball.webp" },
  { word: "עטלף", en: "Bat", img: "/words/junior/bat.webp" },
  { word: "סוללה", en: "Battery", img: "/words/junior/battery.webp" },
  { word: "אופניים", en: "Bicycle", img: "/words/junior/bicycle.webp" },
  { word: "לוח", en: "Board", img: "/words/junior/board.webp" },
  { word: "סירה", en: "Boat", img: "/words/junior/boat.webp" },
  { word: "מגפיים", en: "Boots", img: "/words/junior/boots.webp" },
  { word: "באולינג", en: "Bowling", img: "/words/junior/bowling.webp" },
  { word: "גשר", en: "Bridge", img: "/words/junior/bridge.webp" },
  { word: "דחפור", en: "Bulldozer", img: "/words/junior/bulldozer.webp" },
  { word: "אוטובוס", en: "Bus", img: "/words/junior/bus.webp" },
  { word: "כבל", en: "Cable", img: "/words/junior/cable.webp" },
  { word: "מחשבון", en: "Calculator", img: "/words/junior/calculator.webp" },
  { word: "גמל", en: "Camel", img: "/words/junior/camel.webp" },
  { word: "מצלמה", en: "Camera", img: "/words/junior/camera.webp" },
  { word: "נר", en: "Candle", img: "/words/junior/candle.webp" },
  { word: "טירה", en: "Castle", img: "/words/junior/castle.webp" },
  { word: "צ'לו", en: "Cello", img: "/words/junior/cello.webp" },
  { word: "זיקית", en: "Chameleon", img: "/words/junior/chameleon.webp" },
  { word: "גבינה", en: "Cheese", img: "/words/junior/cheese.webp" },
  { word: "ברדלס", en: "Cheetah", img: "/words/junior/cheetah.webp" },
  { word: "שחמט", en: "Chess", img: "/words/junior/chess.webp" },
  { word: "שימפנזה", en: "Chimpanzee", img: "/words/junior/chimpanzee.webp" },
  { word: "שוקולד", en: "Chocolate", img: "/words/junior/chocolate.webp" },
  { word: "קוברה", en: "Cobra", img: "/words/junior/cobra.webp" },
  { word: "מצפן", en: "Compass", img: "/words/junior/compass.webp" },
  { word: "מנוף", en: "Crane", img: "/words/junior/crane.webp" },
  { word: "תנין", en: "Crocodile", img: "/words/junior/crocodile.webp" },
  { word: "אייל", en: "Deer", img: "/words/junior/deer.webp" },
  { word: "מדבר", en: "Desert", img: "/words/junior/desert.webp" },
  { word: "צוללן", en: "Diver", img: "/words/junior/diver.webp" },
  { word: "דולפין", en: "Dolphin", img: "/words/junior/dolphin.webp" },
  { word: "דונאט", en: "Donut", img: "/words/junior/donut.webp" },
  { word: "מקדחה", en: "Drill", img: "/words/junior/drill.webp" },
  { word: "רחפן", en: "Drone", img: "/words/junior/drone.webp" },
  { word: "תופים", en: "Drums", img: "/words/junior/drums.webp" },
  { word: "סייף", en: "Fencing", img: "/words/junior/fencing.webp" },
  { word: "כבאי", en: "Firefighter", img: "/words/junior/firefighter.webp" },
  { word: "דג", en: "Fish", img: "/words/junior/fish.webp" },
  { word: "פלמינגו", en: "Flamingo", img: "/words/junior/flamingo.webp" },
  { word: "חליל", en: "Flute", img: "/words/junior/flute.webp" },
  { word: "יער", en: "Forest", img: "/words/junior/forest.webp" },
  { word: "שועל", en: "Fox", img: "/words/junior/fox.webp" },
  { word: "מקרר", en: "Fridge", img: "/words/junior/fridge.webp" },
  { word: "צפרדע", en: "Frog", img: "/words/junior/frog.webp" },
  { word: "מתנה", en: "Gift", img: "/words/junior/gift.webp" },
  { word: "גלובוס", en: "Globe", img: "/words/junior/globe.webp" },
  { word: "גולף", en: "Golf", img: "/words/junior/golf.webp" },
  { word: "גורילה", en: "Gorilla", img: "/words/junior/gorilla.webp" },
  { word: "ענבים", en: "Grape", img: "/words/junior/grape.webp" },
  { word: "גיטרה", en: "Guitar", img: "/words/junior/guitar.webp" },
  { word: "פטיש", en: "Hammer", img: "/words/junior/hammer.webp" },
  { word: "יד", en: "Hand", img: "/words/junior/hand.webp" },
  { word: "נבל", en: "Harp", img: "/words/junior/harp.webp" },
  { word: "אוזניות", en: "Headphones", img: "/words/junior/headphones.webp" },
  { word: "קיפוד", en: "Hedgehog", img: "/words/junior/hedgehog.webp" },
  { word: "מסוק", en: "Helicopter", img: "/words/junior/helicopter.webp" },
  { word: "מרקר", en: "Highlighter", img: "/words/junior/highlighter.webp" },
  { word: "היפופוטם", en: "Hippo", img: "/words/junior/hippo.webp" },
  { word: "דבש", en: "Honey", img: "/words/junior/honey.webp" },
  { word: "נקניקייה", en: "Hotdog", img: "/words/junior/hotdog.webp" },
  { word: "גלידה", en: "Ice Cream", img: "/words/junior/ice_cream.webp" },
  { word: "מגהץ", en: "Iron", img: "/words/junior/iron.webp" },
  { word: "מדוזה", en: "Jellyfish", img: "/words/junior/jellyfish.webp" },
  { word: "מטוס סילון", en: "Jet", img: "/words/junior/jet.webp" },
  { word: "קנגורו", en: "Kangaroo", img: "/words/junior/kangaroo.webp" },
  { word: "קומקום", en: "Kettle", img: "/words/junior/kettle.webp" },
  { word: "מפתח", en: "Key", img: "/words/junior/key.webp" },
  { word: "מקלדת", en: "Keyboard", img: "/words/junior/keyboard.webp" },
  { word: "קואלה", en: "Koala", img: "/words/junior/koala.webp" },
  { word: "סולם", en: "Ladder", img: "/words/junior/ladder.webp" },
  { word: "חיפושית", en: "Ladybug", img: "/words/junior/ladybug.webp" },
  { word: "נורה", en: "Light Bulb", img: "/words/junior/light_bulb.webp" },
  { word: "ברק", en: "Lightning", img: "/words/junior/lightning.webp" },
  { word: "אריה", en: "Lion", img: "/words/junior/lion.webp" },
  { word: "מנעול", en: "Lock", img: "/words/junior/lock.webp" },
  { word: "זכוכית מגדלת", en: "Magnifying Glass", img: "/words/junior/magnifying_glass.webp" },
  { word: "מדליה", en: "Medal", img: "/words/junior/medal.webp" },
  { word: "קוף", en: "Monkey", img: "/words/junior/monkey.webp" },
  { word: "אופנוע", en: "Motorcycle", img: "/words/junior/motorcycle.webp" },
  { word: "תפוז", en: "Orange", img: "/words/junior/orange.webp" },
  { word: "יען", en: "Ostrich", img: "/words/junior/ostrich.webp" },
  { word: "לוטרה", en: "Otter", img: "/words/junior/otter.webp" },
  { word: "פנקייק", en: "Pancake", img: "/words/junior/pancake.webp" },
  { word: "פנדה", en: "Panda", img: "/words/junior/panda.webp" },
  { word: "תוכי", en: "Parrot", img: "/words/junior/parrot.webp" },
  { word: "טווס", en: "Peacock", img: "/words/junior/peacock.webp" },
  { word: "עפרונות", en: "Pencils", img: "/words/junior/pencils.webp" },
  { word: "פאי", en: "Pie", img: "/words/junior/pie.webp" },
  { word: "אננס", en: "Pineapple", img: "/words/junior/pineapple.webp" },
  { word: "פיצה", en: "Pizza", img: "/words/junior/pizza.webp" },
  { word: "פלייר", en: "Pliers", img: "/words/junior/pliers.webp" },
  { word: "פופקורן", en: "Popcorn", img: "/words/junior/popcorn.webp" },
  { word: "מדפסת", en: "Printer", img: "/words/junior/printer.webp" },
  { word: "קרנף", en: "Rhino", img: "/words/junior/rhino.webp" },
  { word: "טבעת", en: "Ring", img: "/words/junior/ring.webp" },
  { word: "רקטה", en: "Rocket", img: "/words/junior/rocket.webp" },
  { word: "גלגיליות", en: "Rollerblades", img: "/words/junior/rollerblades.webp" },
  { word: "קורקינט", en: "Scooter", img: "/words/junior/scooter.webp" },
  { word: "עקרב", en: "Scorpion", img: "/words/junior/scorpion.webp" },
  { word: "סקי", en: "Skiing", img: "/words/junior/skiing.webp" },
  { word: "עצלן", en: "Sloth", img: "/words/junior/sloth.webp" },
  { word: "נחש", en: "Snake", img: "/words/junior/snake.webp" },
  { word: "סבון", en: "Soap", img: "/words/junior/soap.webp" },
  { word: "כדורגל", en: "Soccer", img: "/words/junior/soccer.webp" },
  { word: "סנאי", en: "Squirrel", img: "/words/junior/squirrel.webp" },
  { word: "מהדק", en: "Stapler", img: "/words/junior/stapler.webp" },
  { word: "כוכב ים", en: "Starfish", img: "/words/junior/starfish.webp" },
  { word: "סטייק", en: "Steak", img: "/words/junior/steak.webp" },
  { word: "מזוודה", en: "Suitcase", img: "/words/junior/suitcase.webp" },
  { word: "סושי", en: "Sushi", img: "/words/junior/sushi.webp" },
  { word: "ברבור", en: "Swan", img: "/words/junior/swan.webp" },
  { word: "טנק", en: "Tank", img: "/words/junior/tank.webp" },
  { word: "טניס", en: "Tennis", img: "/words/junior/tennis.webp" },
  { word: "אוהל", en: "Tent", img: "/words/junior/tent.webp" },
  { word: "מבחנה", en: "Test Tube", img: "/words/junior/test_tube.webp" },
  { word: "טוסטר", en: "Toaster", img: "/words/junior/toaster.webp" },
  { word: "מברשת שיניים", en: "Toothbrush", img: "/words/junior/toothbrush.webp" },
  { word: "טרקטור", en: "Tractor", img: "/words/junior/tractor.webp" },
  { word: "רכבת", en: "Train", img: "/words/junior/train.webp" },
  { word: "גביע", en: "Trophy", img: "/words/junior/trophy.webp" },
  { word: "חצוצרה", en: "Trumpet", img: "/words/junior/trumpet.webp" },
  { word: "צב", en: "Turtle", img: "/words/junior/turtle.webp" },
  { word: "מטריה", en: "Umbrella", img: "/words/junior/umbrella.webp" },
  { word: "שואב אבק", en: "Vacuum Cleaner", img: "/words/junior/vacuum_cleaner.webp" },
  { word: "כינור", en: "Violin", img: "/words/junior/violin.webp" },
  { word: "הר געש", en: "Volcano", img: "/words/junior/volcano.webp" },
  { word: "וופל", en: "Waffle", img: "/words/junior/waffle.webp" },
  { word: "ארנק", en: "Wallet", img: "/words/junior/wallet.webp" },
  { word: "מפל", en: "Waterfall", img: "/words/junior/waterfall.webp" },
  { word: "לווייתן", en: "Whale", img: "/words/junior/whale.webp" },
  { word: "משרוקית", en: "Whistle", img: "/words/junior/whistle.webp" },
  { word: "טחנת רוח", en: "Windmill", img: "/words/junior/windmill.webp" }
];