// app/lib/words/junior.ts
import { WordItem } from "../../game.config";

export const JUNIOR_WORDS: WordItem[] = [
  { word: "מַזְגָן", en: "Air Conditioner", img: "/words/junior/air_conditioner.webp" },
  { word: "אַסְטְרוֹנָאוּט", en: "Astronaut", img: "/words/junior/astronaut.webp" },
  { word: "כַּדּוּרֶסֶל", en: "Basketball", img: "/words/junior/basketball.webp" },
  { word: "סוֹלְלָה", en: "Battery", img: "/words/junior/battery.webp" },
  { word: "אוֹפַנַּיִם", en: "Bicycle", img: "/words/junior/bicycle.webp" },
  { word: "לוּחַ", en: "Board", img: "/words/junior/board.webp" },
  { word: "סִיר", en: "Boat", img: "/words/junior/boat.webp" },
  { word: "גֶּשֶׁר", en: "Bridge", img: "/words/junior/bridge.webp" },
  { word: "כֶּבֶל", en: "Cable", img: "/words/junior/cable.webp" },
  { word: "מַחְשֵׁבוֹן", en: "Calculator", img: "/words/junior/calculator.webp" },
  { word: "מַצְלֵמָה", en: "Camera", img: "/words/junior/camera.webp" },
  { word: "מַצְפֵּן", en: "Compass", img: "/words/junior/compass.webp" },
  { word: "מִדְבָּר", en: "Desert", img: "/words/junior/desert.webp" },
  { word: "צוללן", en: "Diver", img: "/words/junior/diver.webp" },
  { word: "מַקְדֵּחָה", en: "Drill", img: "/words/junior/drill.webp" },
  { word: "כַּבַּאי", en: "Firefighter", img: "/words/junior/firefighter.webp" },
  { word: "יַעַר", en: "Forest", img: "/words/junior/forest.webp" },
  { word: "מְקָרֵר", en: "Fridge", img: "/words/junior/fridge.webp" },
  { word: "גְּלוֹבּוּס", en: "Globe", img: "/words/junior/globe.webp" },
  { word: "פַּטִּישׁ", en: "Hammer", img: "/words/junior/hammer.webp" },
  { word: "יָד", en: "Hand", img: "/words/junior/hand.webp" },
  { word: "אוֹזְנִיּוֹת", en: "Headphones", img: "/words/junior/headphones.webp" },
  { word: "הֶלִיקוֹפְּטֶר", en: "Helicopter", img: "/words/junior/helicopter.webp" },
  { word: "מַרְקֶר", en: "Highlighter", img: "/words/junior/highlighter.webp" },
  { word: "מַגְהֵץ", en: "Iron", img: "/words/junior/iron.webp" },
  { word: "מָטוֹס סִילוֹן", en: "Jet", img: "/words/junior/jet.webp" },
  { word: "קַמְקוּם חַשְׁמַלִּי", en: "Kettle", img: "/words/junior/kettle.webp" },
  { word: "מַקְלֶדֶת", en: "Keyboard", img: "/words/junior/keyboard.webp" },
  { word: "סֻלָּם", en: "Ladder", img: "/words/junior/ladder.webp" },
  { word: "נּוּרָה", en: "Light Bulb", img: "/words/junior/light_bulb.webp" },
  { word: "מַדַּלְיָה", en: "Medal", img: "/words/junior/medal.webp" },
  { word: "עֶפְרוֹנוֹת", en: "Pencils", img: "/words/junior/pencils.webp" },
  { word: "מַדְפֶּסֶת", en: "Printer", img: "/words/junior/printer.webp" },
  { word: "גַּלְגִּלַּיִם", en: "Rollerblades", img: "/words/junior/rollerblades.webp" },
  { word: "קוֹרְקִינֶט", en: "Scooter", img: "/words/junior/scooter.webp" },
  { word: "כַּדּוּרֶגֶל", en: "Soccer", img: "/words/junior/soccer.webp" },
  { word: "מַהְדֵּק", en: "Stapler", img: "/words/junior/stapler.webp" },
  { word: "מִזְוָדָה", en: "Suitcase", img: "/words/junior/suitcase.webp" },
  { word: "טֶנִיס", en: "Tennis", img: "/words/junior/tennis.webp" },
  { word: "אוֹהֶל", en: "Tent", img: "/words/junior/tent.webp" },
  { word: "טוֹסְטֶר", en: "Toaster", img: "/words/junior/toaster.webp" },
  { word: "טְרַקְטוֹר", en: "Tractor", img: "/words/junior/tractor.webp" },
  { word: "שׁוֹאֵב אָבָק", en: "Vacuum Cleaner", img: "/words/junior/vacuum_cleaner.webp" },
  { word: "הַר גַּעַשׁ", en: "Volcano", img: "/words/junior/volcano.webp" },
  { word: "אַרְנָק", en: "Wallet", img: "/words/junior/wallet.webp" },
  { word: "מַפָּל", en: "Waterfall", img: "/words/junior/waterfall.webp" },
  { word: "מַשְׁרוֹקִית", en: "Whistle", img: "/words/junior/whistle.webp" }
];