import { WordItem } from "../../game.config";

export const JUNIOR_ONLY: WordItem[] = [
  { word: "טניס", en: "tennis", img: "/words/junior/tennis.webp" },
  { word: "רולרבליידס", en: "rollerblades", img: "/words/junior/rollerblades.webp" },
  { word: "מטוס סילון", en: "jet", img: "/words/junior/jet.webp" },
  { word: "צוללן", en: "diver", img: "/words/junior/diver.webp" },
  { word: "מדבר", en: "desert", img: "/words/junior/desert.webp" },
  { word: "יער", en: "forest", img: "/words/junior/forest.webp" },
  { word: "הר געש", en: "volcano", img: "/words/junior/volcano.webp" },
  { word: "מפל", en: "waterfall", img: "/words/junior/waterfall.webp" },
  { word: "סירה", en: "boat", img: "/words/junior/boat.webp" },
  { word: "מזוודה", en: "suitcase", img: "/words/junior/suitcase.webp" },
  { word: "ארנק", en: "wallet", img: "/words/junior/wallet.webp" },
  { word: "מצפן", en: "compass", img: "/words/junior/compass.webp" },
  { word: "גלובוס", en: "globe", img: "/words/junior/globe.webp" },
  { word: "פטיש", en: "hammer", img: "/words/junior/hammer.webp" },
  { word: "גשר", en: "bridge", img: "/words/junior/bridge.webp" },
  { word: "כבל", en: "cable", img: "/words/junior/cable.webp" },
  { word: "פנדה", en: "panda", img: "/words/junior/panda.webp" },
  { word: "קואלה", en: "koala", img: "/words/junior/koala.webp" },
  { word: "קנגורו", en: "kangaroo", img: "/words/junior/kangaroo.webp" },
  { word: "גורילה", en: "gorilla", img: "/words/junior/gorilla.webp" },
  { word: "תנין", en: "crocodile", img: "/words/junior/crocodile.webp" },
  { word: "לווייתן", en: "whale", img: "/words/junior/whale.webp" },
  { word: "דולפין", en: "dolphin", img: "/words/junior/dolphin.webp" },
  { word: "כוכב ים", en: "starfish", img: "/words/junior/starfish.webp" },
  { word: "פלמינגו", en: "flamingo", img: "/words/junior/flamingo.webp" },
  { word: "ברבור", en: "swan", img: "/words/junior/swan.webp" },
  { word: "סנאי", en: "squirrel", img: "/words/junior/squirrel.webp" },
  { word: "אייל", en: "deer", img: "/words/junior/deer.webp" },
  { word: "סטייק", en: "steak", img: "/words/junior/steak.webp" },
  { word: "גבינה", en: "cheese", img: "/words/junior/cheese.webp" },
  { word: "דבש", en: "honey", img: "/words/junior/honey.webp" },
  { word: "שוקולד", en: "chocolate", img: "/words/junior/chocolate.webp" },
  { word: "עוגה", en: "cake", img: "/words/junior/cake.webp" },
  { word: "דונאט", en: "donut", img: "/words/junior/donut.webp" },
  { word: "פנקייק", en: "pancake", img: "/words/junior/pancake.webp" },
  { word: "וופל", en: "waffle", img: "/words/junior/waffle.webp" },
  { word: "פאי", en: "pie", img: "/words/junior/pie.webp" },
  { word: "גיטרה", en: "guitar", img: "/words/junior/guitar.webp" },
  { word: "כינור", en: "violin", img: "/words/junior/violin.webp" },
  { word: "חצוצרה", en: "trumpet", img: "/words/junior/trumpet.webp" },
  { word: "נבל", en: "harp", img: "/words/junior/harp.webp" },
  { word: "רקטה", en: "rocket", img: "/words/junior/rocket.webp" },
  { word: "טירה", en: "castle", img: "/words/junior/castle.webp" },
  { word: "טחנת רוח", en: "windmill", img: "/words/junior/windmill.webp" },
  { word: "סבון", en: "soap", img: "/words/junior/soap.webp" },
  { word: "מנעול", en: "lock", img: "/words/junior/lock.webp" },
  { word: "מטריה", en: "umbrella", img: "/words/junior/umbrella.webp" },
  { word: "מבחנה", en: "test_tube", img: "/words/junior/test_tube.webp" },
  { word: "ברק", en: "lightning", img: "/words/junior/lightning.webp" },
  { word: "שימפנזה", en: "chimpanzee", img: "/words/junior/chimpanzee.webp" },
  { word: "קוברה", en: "cobra", img: "/words/junior/cobra.webp" },
  { word: "מדוזה", en: "jellyfish", img: "/words/junior/jellyfish.webp" },
  { word: "יען", en: "ostrich", img: "/words/junior/ostrich.webp" },
  { word: "לוטרה", en: "otter", img: "/words/junior/otter.webp" },
  { word: "באולינג", en: "bowling", img: "/words/junior/bowling.webp" },
  { word: "סיוף", en: "fencing", img: "/words/junior/fencing.webp" },
  { word: "גולף", en: "golf", img: "/words/junior/golf.webp" },
  { word: "סקי", en: "skiing", img: "/words/junior/skiing.webp" },
  { word: "פלייר", en: "pliers", img: "/words/junior/pliers.webp" },
  { word: "רחפן", en: "drone", img: "/words/junior/drone.webp" },
  { word: "מיקרוסקופ", en: "microscope", img: "/words/junior/microscope.webp" },
  { word: "טלסקופ", en: "telescope", img: "/words/junior/telescope.webp" },
  { word: "מצנח", en: "parachute", img: "/words/junior/parachute.webp" },
  { word: "קליידוסקופ", en: "kaleidoscope", img: "/words/junior/kaleidoscope.webp" },
  { word: "פרסה", en: "horseshoe", img: "/words/junior/horseshoe.webp" },
  { word: "מגנט", en: "magnet", img: "/words/junior/magnet.webp" },
  { word: "עוגן", en: "anchor", img: "/words/junior/anchor.webp" },
  { word: "משקפת", en: "binoculars", img: "/words/junior/binoculars.webp" },
  { word: "סטטוסקופ", en: "stethoscope", img: "/words/junior/stethoscope.webp" },
  { word: "מיקרופון", en: "microphone", img: "/words/junior/microphone.webp" },
  { word: "מגאפון", en: "megaphone", img: "/words/junior/megaphone.webp" },
  { word: "רמקול", en: "speaker", img: "/words/junior/speaker.webp" },
  { word: "מקלדת", en: "keyboard", img: "/words/junior/keyboard.webp" },
  { word: "עכבר", en: "mouse", img: "/words/junior/mouse.webp" },
  { word: "מסך", en: "monitor", img: "/words/junior/monitor.webp" },
  { word: "לפטופ", en: "laptop", img: "/words/junior/laptop.webp" },
  { word: "טאבלט", en: "tablet", img: "/words/junior/tablet.webp" },
  { word: "סמארטפון", en: "smartphone", img: "/words/junior/smartphone.webp" },
  { word: "שעון יד", en: "watch", img: "/words/junior/watch.webp" },
  { word: "משקפי שמש", en: "sunglasses", img: "/words/junior/sunglasses.webp" },
  { word: "תיק גב", en: "backpack", img: "/words/junior/backpack.webp" },
  { word: "מנורת לילה", en: "lamp", img: "/words/junior/lamp.webp" },
  { word: "מראה", en: "mirror", img: "/words/junior/mirror.webp" },
  { word: "מברשת שיער", en: "hairbrush", img: "/words/junior/hairbrush.webp" },
  { word: "מייבש שיער", en: "hairdryer", img: "/words/junior/hairdryer.webp" },
  { word: "מכונת גילוח", en: "shaver", img: "/words/junior/shaver.webp" },
  { word: "בושם", en: "perfume", img: "/words/junior/perfume.webp" },
  { word: "ליפסטיק", en: "lipstick", img: "/words/junior/lipstick.webp" },
  { word: "לק לציפורניים", en: "nail_polish", img: "/words/junior/nail_polish.webp" },
  { word: "עגילים", en: "earrings", img: "/words/junior/earrings.webp" },
  { word: "שרשרת", en: "necklace", img: "/words/junior/necklace.webp" },
  { word: "צמיד", en: "bracelet", img: "/words/junior/bracelet.webp" },
  { word: "חגורה", en: "belt", img: "/words/junior/belt.webp" },
  { word: "עניבה", en: "tie", img: "/words/junior/tie.webp" },
  { word: "צעיף", en: "scarf", img: "/words/junior/scarf.webp" },
  { word: "כפפות", en: "gloves", img: "/words/junior/gloves.webp" },
  { word: "גרביים", en: "socks", img: "/words/junior/socks.webp" },
  { word: "מכנסיים", en: "pants", img: "/words/junior/pants.webp" },
  { word: "חולצה", en: "shirt", img: "/words/junior/shirt.webp" },
  { word: "שמלה", en: "dress", img: "/words/junior/dress.webp" },
  { word: "חצאית", en: "skirt", img: "/words/junior/skirt.webp" },
  { word: "מעיל", en: "jacket", img: "/words/junior/jacket.webp" },
  { word: "בגד ים", en: "swimsuit", img: "/words/junior/swimsuit.webp" },
  { word: "מגבת", en: "towel", img: "/words/junior/towel.webp" },
  { word: "כרית", en: "pillow", img: "/words/junior/pillow.webp" },
  { word: "שמיכה", en: "blanket", img: "/words/junior/blanket.webp" },
  { word: "מיטה", en: "bed", img: "/words/junior/bed.webp" },
  { word: "ארון", en: "closet", img: "/words/junior/closet.webp" },
  { word: "שולחן", en: "table", img: "/words/junior/table.webp" },
  { word: "כיסא", en: "chair", img: "/words/junior/chair.webp" },
  { word: "ספה", en: "sofa", img: "/words/junior/sofa.webp" },
  { word: "שטיח", en: "rug", img: "/words/junior/rug.webp" },
  { word: "וילון", en: "curtain", img: "/words/junior/curtain.webp" },
  { word: "תמונה", en: "picture", img: "/words/junior/picture.webp" },
  { word: "עציץ", en: "plant", img: "/words/junior/plant.webp" },
  { word: "אגרטל", en: "vase", img: "/words/junior/vase.webp" },
  { word: "שעון קיר", en: "clock", img: "/words/junior/clock.webp" },
  { word: "מפתחות", en: "keys", img: "/words/junior/keys.webp" },
  { word: "מטרייה", en: "umbrella", img: "/words/junior/umbrella.webp" },
  { word: "פנס", en: "flashlight", img: "/words/junior/flashlight.webp" },
  { word: "סוללות", en: "batteries", img: "/words/junior/batteries.webp" },
  { word: "מטען", en: "charger", img: "/words/junior/charger.webp" },
  { word: "שלט", en: "remote", img: "/words/junior/remote.webp" },
  { word: "משקפיים", en: "glasses", img: "/words/junior/glasses.webp" },
  { word: "עט", en: "pen", img: "/words/junior/pen.webp" },
  { word: "עיפרון", en: "pencil", img: "/words/junior/pencil.webp" },
  { word: "מחברת", en: "notebook", img: "/words/junior/notebook.webp" },
  { word: "ספר", en: "book", img: "/words/junior/book.webp" },
  { word: "מספריים", en: "scissors", img: "/words/junior/scissors.webp" },
  { word: "דבק", en: "glue", img: "/words/junior/glue.webp" },
  { word: "סרגל", en: "ruler", img: "/words/junior/ruler.webp" },
  { word: "מחק", en: "eraser" , img: "/words/junior/eraser.webp" }
];