import { WordItem } from "../../game.config";

export const TEEN_WORDS: WordItem[] = [
  // --- טכנולוגיה ודיגיטל ---
  { word: "אלגוריתם", en: "Algorithm" }, { word: "סייבר", en: "Cyber" },
  { word: "בינה מלאכותית", en: "AI" }, { word: "ויראלי", en: "Viral" },
  { word: "סטרימינג", en: "Streaming" }, { word: "פודקאסט", en: "Podcast" },
  { word: "משפיענית", en: "Influencer" }, { word: "גיימינג", en: "Gaming" },
  { word: "שרת", en: "Server" }, { word: "אפליקציה", en: "Application" },
  { word: "ענן", en: "Cloud storage" }, { word: "סיסמה", en: "Password" },
  { word: "האקר", en: "Hacker" }, { word: "מציאות מדומה", en: "VR" },
  { word: "טאבלט", en: "Tablet" }, { word: "בלוטות'", en: "Bluetooth" },
  { word: "וייפיי", en: "Wi-Fi" }, { word: "מטען נייד", en: "Power bank" },
  { word: "סלפי", en: "Selfie" }, { word: "פילטר", en: "Filter" },
  { word: "פורטנייט", en: "Fortnite" }, { word: "דיסקורד", en: "Discord" },
  { word: "טיקטוק", en: "TikTok" }, { word: "סטורי", en: "Story" },
  { word: "רילס", en: "Reels" }, { word: "האשטאג", en: "Hashtag" },
  { word: "מנוי", en: "Subscriber" }, { word: "צפייה", en: "View" },
  { word: "לייב", en: "Live stream" }, { word: "נוטיפיקציה", en: "Notification" },

  // --- לימודים וצבא ---
  { word: "בגרות", en: "Matriculation" }, { word: "ללמוד למבחן", en: "Study for a test" },
  { word: "שיעור חופשי", en: "Free period" }, { word: "הפסקה פעילה", en: "Active break" },
  { word: "טיול שנתי", en: "Annual school trip" }, { word: "מועצת תלמידים", en: "Student council" },
  { word: "צו ראשון", en: "First call-up (Army)" }, { word: "גיבוש", en: "Selection process" },
  { word: "טירונות", en: "Basic training" }, { word: "מדים", en: "Uniform" },
  { word: "שירות לאומי", en: "National service" }, { word: "שנת שירות", en: "Service year" },
  { word: "תנועת נוער", en: "Youth movement" }, { word: "מחנה קיץ", en: "Summer camp" },
  { word: "הדרכה", en: "Guidance/Instruction" }, { word: "מדריך", en: "Counselor" },

  // --- פנאי, חברה ובילוים ---
  { word: "קניון", en: "Mall" }, { word: "באולינג", en: "Bowling" },
  { word: "חדר בריחה", en: "Escape room" }, { word: "מסיבת פיג'מות", en: "Sleepover" },
  { word: "קולנוע", en: "Cinema" }, { word: "הופעה", en: "Concert" },
  { word: "פסטיבל", en: "Festival" }, { word: "ים", en: "Beach" },
  { word: "חדר כושר", en: "Gym" }, { word: "אימון", en: "Workout" },
  { word: "אוזניות", en: "Headphones" }, { word: "רמקול", en: "Speaker" },
  { word: "משקפי שמש", en: "Sunglasses" }, { word: "מותג", en: "Brand" },
  { word: "אופנה", en: "Fashion" }, { word: "סטייל", en: "Style" },

  // --- רגשות וסלנג ---
  { word: "דרמה", en: "Drama" }, { word: "קרינג'", en: "Cringe" },
  { word: "גוסט", en: "Ghosting" }, { word: "שיפ", en: "Shipping" },
  { word: "קראש", en: "Crash" }, { word: "מביך", en: "Embarrassing" },
  { word: "חופר", en: "Annoying/Talkative" }, { word: "זורם", en: "Easygoing" },
  { word: "וייב", en: "Vibe" }, { word: "באסה", en: "Bummer" },
  { word: "סבבה", en: "Cool/Okay" }, { word: "תיוג", en: "Tagging" },
  { word: "חסימה", en: "Blocking" }, { word: "הודעה קולית", en: "Voice message" },
  { word: "שיתוף", en: "Share" }, { word: "פרטיות", en: "Privacy" },

  // --- המשך הרשימה להשלמה ל-500 (קיצור לצורך התצוגה, בפועל יש להוסיף עוד כ-400 מילים) ---
  { word: "גיטרה", en: "Guitar" }, { word: "תופים", en: "Drums" },
  { word: "פסנתר", en: "Piano" }, { word: "סקייטבורד", en: "Skateboard" },
  { word: "קורקינט", en: "Scooter" }, { word: "אופניים חשמליים", en: "E-bike" },
  { word: "רישיון נהיגה", en: "Driver's license" }, { word: "שיעור נהיגה", en: "Driving lesson" },
  { word: "טסט", en: "Driving test" }, { word: "עבודה זמנית", en: "Part-time job" },
  { word: "דמי כיס", en: "Pocket money" }, { word: "חיסכון", en: "Savings" },
  { word: "כרטיס אשראי", en: "Credit card" }, { word: "ארנק דיגיטלי", en: "Digital wallet" },
  { word: "משלוח", en: "Delivery" }, { word: "פיצה", en: "Pizza" },
  { word: "המבורגר", en: "Hamburger" }, { word: "סושי", en: "Sushi" },
  { word: "שייק פירות", en: "Fruit shake" }, { word: "גלידה", en: "Ice cream" },
  { word: "מסעדה", en: "Restaurant" }, { word: "בית קפה", en: "Cafe" },
  { word: "חברים", en: "Friends" }, { word: "חברות", en: "Friendship" },
  { word: "סוד", en: "Secret" }, { word: "אמון", en: "Trust" },
  { word: "תחרות", en: "Competition" }, { word: "ניצחון", en: "Victory" },
  { word: "הפסד", en: "Loss" }, { word: "אתגר", en: "Challenge" },
  { word: "הישג", en: "Achievement" }, { word: "מוטיבציה", en: "Motivation" },
  { word: "לחץ", en: "Stress" }, { word: "חרדה", en: "Anxiety" },
  { word: "ביטחון עצמי", en: "Self-confidence" }, { word: "חלום", en: "Dream" },
  { word: "עתיד", en: "Future" }, { word: "בחירה", en: "Choice" },
  { word: "אחריות", en: "Responsibility" }, { word: "עצמאות", en: "Independence" },
  { word: "זהות", en: "Identity" }, { word: "ערכים", en: "Values" },
  { word: "סביבה", en: "Environment" }, { word: "מחזור", en: "Recycling" },
  { word: "התנדבות", en: "Volunteering" }, { word: "קהילה", en: "Community" },
  { word: "תרומה", en: "Contribution" }, { word: "שינוי", en: "Change" },
  { word: "השפעה", en: "Influence" }, { word: "מנהיגות", en: "Leadership" },
  { word: "יצירתיות", en: "Creativity" }, { word: "אמנות", en: "Art" },
  { word: "מוזיקה", en: "Music" }, { word: "ריקוד", en: "Dance" },
  { word: "משחק", en: "Acting" }, { word: "צילום", en: "Photography" },
  { word: "כתיבה", en: "Writing" }, { word: "קריאה", en: "Reading" },
  { word: "ספר", en: "Book" }, { word: "סרט", en: "Movie" },
  { word: "סדרה", en: "Series" }, { word: "דמות", en: "Character" },
  { word: "עלילה", en: "Plot" }, { word: "ספוילר", en: "Spoiler" },
  { word: "מעריץ", en: "Fan" }, { word: "קהל", en: "Audience" },
  { word: "במה", en: "Stage" }, { word: "תאורה", en: "Lighting" },
  { word: "סאונד", en: "Sound" }, { word: "הפקה", en: "Production" },
  { word: "בימוי", en: "Directing" }, { word: "עריכה", en: "Editing" },
  { word: "עיצוב", en: "Design" }, { word: "גרפיקה", en: "Graphics" },
  { word: "אנימציה", en: "Animation" }, { word: "איור", en: "Illustration" },
  { word: "קומיקס", en: "Comics" }, { word: "מנגה", en: "Manga" },
  { word: "אנימה", en: "Anime" }, { word: "קוספליי", en: "Cosplay" },
  { word: "גיימר", en: "Gamer" }, { word: "קונסולה", en: "Console" },
  { word: "בקר", en: "Controller" }, { word: "רזולוציה", en: "Resolution" },
  { word: "פריימים", en: "Frames" }, { word: "לאג", en: "Lag" },
  { word: "פינג", en: "Ping" }, { word: "בוט", en: "Bot" },
  { word: "סקין", en: "Skin" }, { word: "מוד", en: "Mod" },
  { word: "צ'אט", en: "Chat" }, { word: "קבוצה", en: "Group" },
  { word: "שרת", en: "Server" }, { word: "קישור", en: "Link" },
  { word: "כתובת", en: "Address" }, { word: "דפדפן", en: "Browser" },
  { word: "חיפוש", en: "Search" }, { word: "תוצאה", en: "Result" },
  { word: "מידע", en: "Information" }, { word: "ידע", en: "Knowledge" },
  { word: "זיכרון", en: "Memory" }, { word: "אחסון", en: "Storage" },
  { word: "מהירות", en: "Speed" }, { word: "ביצועים", en: "Performance" },
  { word: "סוללה", en: "Battery" }, { word: "טעינה", en: "Charging" },
  { word: "מסך", en: "Screen" }, { word: "מגע", en: "Touch" },
  { word: "מקלדת", en: "Keyboard" }, { word: "עכבר", en: "Mouse" },
  { word: "מצלמה", en: "Camera" }, { word: "מיקרופון", en: "Microphone" },
  { word: "חיבור", en: "Connection" }, { word: "ניתוק", en: "Disconnection" },
  { word: "תקלה", en: "Error" }, { word: "תיקון", en: "Fix" },
  { word: "עדכון", en: "Update" }, { word: "גרסה", en: "Version" },
  { word: "התקנה", en: "Installation" }, { word: "הסרה", en: "Removal" },
  { word: "הגדרות", en: "Settings" }, { word: "חשבון", en: "Account" },
  { word: "פרופיל", en: "Profile" }, { word: "סיסמה", en: "Password" },
  { word: "אבטחה", en: "Security" }, { word: "הגנה", en: "Protection" },
  { word: "פרטיות", en: "Privacy" }, { word: "שיתוף", en: "Share" },
  { word: "תגובה", en: "Comment" }, { word: "לייק", en: "Like" },
  { word: "עוקב", en: "Follower" }, { word: "חבר", en: "Friend" },
  { word: "הודעה", en: "Message" }, { word: "התראה", en: "Alert" },
  { word: "תמונה", en: "Photo" }, { word: "סרטון", en: "Video" },
  { word: "אודיו", en: "Audio" }, { word: "קובץ", en: "File" },
  { word: "תיקייה", en: "Folder" }, { word: "מסמך", en: "Document" },
  { word: "מצגת", en: "Presentation" }, { word: "טבלה", en: "Table" },
  { word: "גרף", en: "Graph" }, { word: "נתונים", en: "Data" },
  { word: "סטטיסטיקה", en: "Statistics" }, { word: "ניתוח", en: "Analysis" },
  { word: "מחקר", en: "Research" }, { word: "מדע", en: "Science" },
  { word: "טכנולוגיה", en: "Technology" }, { word: "הנדסה", en: "Engineering" },
  { word: "מתמטיקה", en: "Mathematics" }, { word: "פיזיקה", en: "Physics" },
  { word: "כימיה", en: "Chemistry" }, { word: "ביולוגיה", en: "Biology" },
  { word: "היסטוריה", en: "History" }, { word: "גיאוגרפיה", en: "Geography" },
  { word: "ספרות", en: "Literature" }, { word: "לשון", en: "Language" },
  { word: "אנגלית", en: "English" }, { word: "ערבית", en: "Arabic" },
  { word: "צרפתית", en: "French" }, { word: "ספרדית", en: "Spanish" },
  { word: "אומנות", en: "Art" }, { word: "מוזיקה", en: "Music" },
  { word: "חינוך גופני", en: "PE" }, { word: "תנ\"ך", en: "Bible" },
  { word: "אזרחות", en: "Civics" }, { word: "שלח", en: "Shelah" },
  { word: "מחויבות אישית", en: "Personal commitment" }, { word: "התנדבות", en: "Volunteer" },
  { word: "טקס", en: "Ceremony" }, { word: "מסיבה", en: "Party" },
  { word: "נשף", en: "Prom" }, { word: "סיום לימודים", en: "Graduation" },
  { word: "חופש גדול", en: "Summer break" }, { word: "חג", en: "Holiday" },
  { word: "סוף שבוע", en: "Weekend" }, { word: "טיול", en: "Trip" },
  { word: "טיסה", en: "Flight" }, { word: "מלון", en: "Hotel" },
  { word: "מזוודה", en: "Suitcase" }, { word: "דרכון", en: "Passport" },
  { word: "מפה", en: "Map" }, { word: "מצפן", en: "Compass" },
  { word: "תרמיל", en: "Backpack" }, { word: "אוהל", en: "Tent" },
  { word: "שק שינה", en: "Sleeping bag" }, { word: "מדורה", en: "Campfire" },
  { word: "מנגל", en: "BBQ" }, { word: "פיקניק", en: "Picnic" },
  { word: "פארק", en: "Park" }, { word: "יער", en: "Forest" },
  { word: "הר", en: "Mountain" }, { word: "נחל", en: "River" },
  { word: "אגם", en: "Lake" }, { word: "מפל", en: "Waterfall" },
  { word: "מדבר", en: "Desert" }, { word: "שקיעה", en: "Sunset" },
  { word: "זריחה", en: "Sunrise" }, { word: "כוכב", en: "Star" },
  { word: "ירח", en: "Moon" }, { word: "שמש", en: "Sun" },
  { word: "ענן", en: "Cloud" }, { word: "גשם", en: "Rain" },
  { word: "שלג", en: "Snow" }, { word: "רוח", en: "Wind" },
  { word: "סערה", en: "Storm" }, { word: "ברק", en: "Lightning" },
  { word: "רעם", en: "Thunder" }, { word: "קשת", en: "Rainbow" },
  { word: "טבע", en: "Nature" }, { word: "בעל חיים", en: "Animal" },
  { word: "צמח", en: "Plant" }, { word: "פרח", en: "Flower" },
  { word: "עץ", en: "Tree" }, { word: "גינה", en: "Garden" },
  { word: "חקלאות", en: "Agriculture" }, { word: "סביבה", en: "Environment" },
  { word: "זיהום", en: "Pollution" }, { word: "מחזור", en: "Recycling" },
  { word: "אנרגיה", en: "Energy" }, { word: "חשמל", en: "Electricity" },
  { word: "מים", en: "Water" }, { word: "אוכל", en: "Food" },
  { word: "שתייה", en: "Drink" }, { word: "בריאות", en: "Health" },
  { word: "כושר", en: "Fitness" }, { word: "ספורט", en: "Sport" },
  { word: "כדורגל", en: "Football" }, { word: "כדורסל", en: "Basketball" },
  { word: "טניס", en: "Tennis" }, { word: "שחייה", en: "Swimming" },
  { word: "ריצה", en: "Running" }, { word: "רכיבה", en: "Riding" },
  { word: "יוגה", en: "Yoga" }, { word: "פילאטיס", en: "Pilates" },
  { word: "אומנויות לחימה", en: "Martial arts" }, { word: "ריקוד", en: "Dancing" },
  { word: "התעמלות", en: "Gymnastics" }, { word: "אתלטיקה", en: "Athletics" },
  { word: "גלישה", en: "Surfing" }, { word: "צלילה", en: "Diving" },
  { word: "שיט", en: "Sailing" }, { word: "חתירה", en: "Rowing" },
  { word: "טיפוס", en: "Climbing" }, { word: "סקי", en: "Skiing" },
  { word: "החלקה", en: "Skating" }, { word: "רולרבליידס", en: "Rollerblades" },
  { word: "קורקינט", en: "Scooter" }, { word: "אופניים", en: "Bicycle" },
  { word: "מכונית", en: "Car" }, { word: "אוטובוס", en: "Bus" },
  { word: "רכבת", en: "Train" }, { word: "מטוס", en: "Airplane" },
  { word: "ספינה", en: "Ship" }, { word: "אופנוע", en: "Motorcycle" },
  { word: "קסדה", en: "Helmet" }, { word: "חגורה", en: "Belt" },
  { word: "בטיחות", en: "Safety" }, { word: "זהירות", en: "Caution" },
  { word: "חוק", en: "Law" }, { word: "משטרה", en: "Police" },
  { word: "עירייה", en: "Municipality" }, { word: "ממשלה", en: "Government" },
  { word: "מדינה", en: "State" }, { word: "עולם", en: "World" },
  { word: "חלל", en: "Space" }, { word: "אסטרונאוט", en: "Astronaut" },
  { word: "חללית", en: "Spaceship" }, { word: "כוכב לכת", en: "Planet" },
  { word: "גלקסיה", en: "Galaxy" }, { word: "טלסקופ", en: "Telescope" },
  { word: "מדע בדיוני", en: "Sci-Fi" }, { word: "פנטזיה", en: "Fantasy" },
  { word: "גיבור על", en: "Superhero" }, { word: "נבל", en: "Villain" },
  { word: "קומיקס", en: "Comics" }, { word: "משחק תפקידים", en: "RPG" },
  { word: "לוח", en: "Board" }, { word: "קלפים", en: "Cards" },
  { word: "קוביות", en: "Dice" }, { word: "אסטרטגיה", en: "Strategy" },
  { word: "מזל", en: "Luck" }, { word: "ניצחון", en: "Victory" },
  { word: "הפסד", en: "Loss" }, { word: "תור", en: "Turn" },
  { word: "כלל", en: "Rule" }, { word: "רמה", en: "Level" },
  { word: "בונוס", en: "Bonus" }, { word: "ניקוד", en: "Score" },
  { word: "שיא", en: "Record" }, { word: "פרס", en: "Prize" },
  { word: "מדליה", en: "Medal" }, { word: "גביע", en: "Trophy" },
  { word: "תעודה", en: "Certificate" }, { word: "הצלחה", en: "Success" },
  { word: "כישלון", en: "Failure" }, { word: "ניסיון", en: "Experience" },
  { word: "למידה", en: "Learning" }, { word: "שיפור", en: "Improvement" },
  { word: "תרגול", en: "Practice" }, { word: "חזרה", en: "Repetition" },
  { word: "זיכרון", en: "Memory" }, { word: "ריכוז", en: "Concentration" },
  { word: "מחשבה", en: "Thought" }, { word: "דמיון", en: "Imagination" },
  { word: "סקרנות", en: "Curiosity" }, { word: "עניין", en: "Interest" },
  { word: "הנאה", en: "Enjoyment" }, { word: "שמחה", en: "Joy" },
  { word: "צחוק", en: "Laughter" }, { word: "חיוך", en: "Smile" },
  { word: "אהבה", en: "Love" }, { word: "חברות", en: "Friendship" },
  { word: "משפחה", en: "Family" }, { word: "הורים", en: "Parents" },
  { word: "אחים", en: "Siblings" }, { word: "סבים", en: "Grandparents" },
  { word: "בית", en: "Home" }, { word: "חדר", en: "Room" },
  { word: "מיטה", en: "Bed" }, { word: "ארון", en: "Closet" },
  { word: "שולחן", en: "Table" }, { word: "כיסא", en: "Chair" },
  { word: "מנורה", en: "Lamp" }, { word: "חלון", en: "Window" },
  { word: "דלת", en: "Door" }, { word: "רצפה", en: "Floor" },
  { word: "קיר", en: "Wall" }, { word: "תקרה", en: "Ceiling" },
  { word: "גינה", en: "Garden" }, { word: "מרפסת", en: "Balcony" },
  { word: "מטבח", en: "Kitchen" }, { word: "מקרר", en: "Fridge" },
  { word: "תנור", en: "Oven" }, { word: "מיקרוגל", en: "Microwave" },
  { word: "קומקום", en: "Kettle" }, { word: "צלחת", en: "Plate" },
  { word: "כוס", en: "Cup" }, { word: "סכו\"ם", en: "Cutlery" },
  { word: "בישול", en: "Cooking" }, { word: "אפייה", en: "Baking" },
  { word: "מתכון", en: "Recipe" }, { word: "טעם", en: "Taste" },
  { word: "ריח", en: "Smell" }, { word: "צבע", en: "Color" },
  { word: "צורה", en: "Shape" }, { word: "גודל", en: "Size" },
  { word: "משקל", en: "Weight" }, { word: "גובה", en: "Height" },
  { word: "מרחק", en: "Distance" }, { word: "זמן", en: "Time" },
  { word: "שעה", en: "Hour" }, { word: "דקה", en: "Minute" },
  { word: "שנייה", en: "Second" }, { word: "יום", en: "Day" },
  { word: "שבוע", en: "Week" }, { word: "חודש", en: "Month" },
  { word: "שנה", en: "Year" }, { word: "עונה", en: "Season" },
  { word: "תאריך", en: "Date" }, { word: "יומן", en: "Diary" },
  { word: "לוח זמנים", en: "Schedule" }, { word: "פגישה", en: "Meeting" },
  { word: "אירוע", en: "Event" }, { word: "חגיגה", en: "Celebration" },
  { word: "מתנה", en: "Gift" }, { word: "ברכה", en: "Greeting" },
  { word: "הפתעה", en: "Surprise" }, { word: "זכרון", en: "Memory" },
  { word: "נוסטלגיה", en: "Nostalgia" }, { word: "הווה", en: "Present" },
  { word: "עתיד", en: "Future" }, { word: "התחלה", en: "Beginning" },
  { word: "סוף", en: "End" }, { word: "אמצע", en: "Middle" },
  { word: "חלק", en: "Part" }, { word: "שלם", en: "Whole" },
  { word: "קבוצה", en: "Group" }, { word: "יחיד", en: "Individual" },
  { word: "זוג", en: "Couple" }, { word: "קהל", en: "Crowd" },
  { word: "חברה", en: "Society" }, { word: "תרבות", en: "Culture" },
  { word: "מסורת", en: "Tradition" }, { word: "מנהג", en: "Custom" },
  { word: "סמל", en: "Symbol" }, { word: "דגל", en: "Flag" },
  { word: "המנון", en: "Anthem" }, { word: "חופש", en: "Freedom" },
  { word: "שוויון", en: "Equality" }, { word: "צדק", en: "Justice" },
  { word: "שלום", en: "Peace" }, { word: "ביטחון", en: "Security" },
  { word: "תקווה", en: "Hope" }, { word: "אמונה", en: "Faith" },
  { word: "אהבה", en: "Love" }, { word: "טוב", en: "Good" },
  { word: "רע", en: "Bad" }, { word: "נכון", en: "Right" },
  { word: "טעות", en: "Wrong" }, { word: "אמת", en: "Truth" },
  { word: "שקר", en: "Lie" }, { word: "ספק", en: "Doubt" },
  { word: "שאלה", en: "Question" }, { word: "תשובה", en: "Answer" },
  { word: "פתרון", en: "Solution" }, { word: "בעיה", en: "Problem" },
  { word: "הזדמנות", en: "Opportunity" }, { word: "החלטה", en: "Decision" },
  { word: "פעולה", en: "Action" }, { word: "תוצאה", en: "Consequence" },
  { word: "אחריות", en: "Responsibility" }, { word: "לקח", en: "Lesson" },
  { word: "ניסיון", en: "Experience" }, { word: "צמיחה", en: "Growth" },
  { word: "שינוי", en: "Change" }, { word: "התפתחות", en: "Development" },
  { word: "יצירה", en: "Creation" }, { word: "המצאה", en: "Invention" },
  { word: "גילוי", en: "Discovery" }, { word: "חיפוש", en: "Search" },
  { word: "מסע", en: "Journey" }, { word: "הרפתקה", en: "Adventure" },
  { word: "אתגר", en: "Challenge" }, { word: "מאמץ", en: "Effort" },
  { word: "התמדה", en: "Persistence" }, { word: "נחישות", en: "Determination" },
  { word: "אומץ", en: "Courage" }, { word: "פחד", en: "Fear" },
  { word: "כוח", en: "Strength" }, { word: "חולשה", en: "Weakness" },
  { word: "גאווה", en: "Pride" }, { word: "צניעות", en: "Humility" },
  { word: "כבוד", en: "Respect" }, { word: "סובלנות", en: "Tolerance" },
  { word: "נדיבות", en: "Generosity" }, { word: "חסד", en: "Kindness" },
  { word: "חמלה", en: "Compassion" }, { word: "אמפתיה", en: "Empathy" },
  { word: "הקשבה", en: "Listening" }, { word: "הבנה", en: "Understanding" },
  { word: "תקשורת", en: "Communication" }, { word: "דיאלוג", en: "Dialogue" },
  { word: "שיתוף פעולה", en: "Cooperation" }, { word: "אחדות", en: "Unity" },
  { word: "שלום", en: "Peace" }
];